### ISSUE TITLE
Field Object:  TypeError: __init__() got an unexpected keyword argument 'title'

### ISSUE THREAD

**Issue by rbcabreraUPM** [samuelcolvin/pydantic#1756] opened 2020-07-23 09:01 UTC
I am getting an error of ` TypeError: __init__() got an unexpected keyword argument 'title'`

this used to work on an older version of pydantic/fastapi.

any suggestions? I am using the latest version of pydantic and fastapi
```
from pydantic import BaseModel
from pydantic.fields import Field
from enum import Enum
from typing import List

class PriorityGatewaySchema(BaseModel):
    gatewayName:  str = Field(..., title="OTP Gateway Name")
    gatewayCode:  str = Field(..., title="OTP Code")
```

**Comment by PrettyWood** [comment] 2020-07-23 09:17
Hi @rbcabreraUPM 
Please follow the template for issues as I can't reproduce your error.
Can you run `python -c "import pydantic.utils; print(pydantic.utils.version_info())"` and display the output ?
Can you confirm that running the code above (and only this code) raises the error ?

**Comment by PrettyWood** [comment] 2020-08-04 21:59
@rbcabreraUPM Following my previous post, I'm closing the issue. Please reopen one if needed

**Closed by PrettyWood** 2020-08-04 21:59 UTC
Labels: question
