### ISSUE TITLE
Bug?: Doesn't seem to work with mypy at all

### ISSUE THREAD

**Issue by jasonkuhrt** [samuelcolvin/pydantic#260] opened 2018-09-08 02:43 UTC
```
$ mypy --version
mypy 0.620

$ cat dialogue/kappa/minimal.py
import pydantic

class Response(pydantic.BaseModel):
    body: str

test1 = Response()
test2 = Response(body=1)

$ mypy --ignore-missing-imports --follow-imports=skip --strict-optional dialogue/kappa/minimal.py
```

I expected mypy to raise errors. Am I missing something?

**Comment by samuelcolvin** [comment] 2018-09-10 09:42
duplicate of #245?

**Closed by samuelcolvin** 2018-09-10 09:42 UTC

**Comment by jasonkuhrt** [comment] 2018-09-10 12:56
I don't know enough to really say if its related but certainly could be! I'll track that one for now... thanks!

**Comment by samuelcolvin** [comment] 2018-09-10 12:58
i'll add a note with my understanding on that issue to keep things in one place.
