### ISSUE TITLE
Converting self-referencing datasets to pydantic's dataset raises `RecursionError: maximum recursion depth exceeded while calling a Python object`

### ISSUE THREAD

**Issue by Wicker25** [samuelcolvin/pydantic#4209] opened 2022-07-04 19:47 UTC
### Checks

* [X] I added a descriptive title to this issue
* [X] I have searched (google, github) for similar issues and couldn't find anything
* [X] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug
Converting self-referencing datasets to pydantic's dataset raises `RecursionError: maximum recursion depth exceeded while calling a Python object`.

The expected behavior should be the one described in https://pydantic-docs.helpmanual.io/usage/dataclasses/#stdlib-dataclasses-and-pydantic-dataclasses .

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.9.1
            pydantic compiled: True
                 install path: /home/master/.../venv/lib/python3.9/site-packages/pydantic
               python version: 3.9.9 (main, Jan  7 2022, 10:36:15)  [GCC 11.1.0]
                     platform: Linux-5.16.15-arch1-1-x86_64-with-glibc2.35
     optional deps. installed: ['dotenv', 'email-validator', 'typing-extensions']

```

```py
from __future__ import annotations

from dataclasses import dataclass
from pydantic.dataclasses import dataclass as pydantic_dataclass


@dataclass
class Node:
    node: Node


if __name__ == '__main__':
    Node2 = pydantic_dataclass(Node)
```

Output:
```
...
  File "pydantic/dataclasses.py", line 186, in pydantic.dataclasses._process_class
    # The name of an attribute on the class where we store the Field
  File "pydantic/main.py", line 988, in pydantic.main.create_model
  File "pydantic/main.py", line 205, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 491, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 421, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 542, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 804, in pydantic.fields.ModelField.populate_validators
  File "pydantic/validators.py", line 683, in find_validators
  File "pydantic/dataclasses.py", line 276, in make_dataclass_validator
    # https://www.python.org/dev/peps/pep-0487/#implementation-details.
  File "pydantic/dataclasses.py", line 265, in pydantic.dataclasses.dataclass
    f'init={self.init!r},'
  File "pydantic/dataclasses.py", line 260, in pydantic.dataclasses.dataclass.wrap
    return ('Field('
  File "pydantic/dataclasses.py", line 159, in pydantic.dataclasses._process_class
    # factory will be used.  This is given a nice repr() which will appear
  File "/home/user/.pyenv/versions/3.9.9/lib/python3.9/dataclasses.py", line 1021, in dataclass
    return wrap(cls)
  File "/home/user/.pyenv/versions/3.9.9/lib/python3.9/dataclasses.py", line 1013, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash, frozen)
  File "/home/user/.pyenv/versions/3.9.9/lib/python3.9/dataclasses.py", line 863, in _process_class
    cls_fields = [_get_field(cls, name, type)
  File "/home/user/.pyenv/versions/3.9.9/lib/python3.9/dataclasses.py", line 863, in <listcomp>
    cls_fields = [_get_field(cls, name, type)
  File "/home/user/.pyenv/versions/3.9.9/lib/python3.9/dataclasses.py", line 685, in _get_field
    f = field(default=default)
  File "/home/user/.pyenv/versions/3.9.9/lib/python3.9/dataclasses.py", line 340, in field
    return Field(default, default_factory, init, repr, hash, compare,
RecursionError: maximum recursion depth exceeded while calling a Python object
```

**Comment by samuelcolvin** [comment] 2022-07-04 19:52
Duplicate of #659.

This is fixed in pydantic-core and will be fixed in v2, but it won't be fixed in pydantic v1.

**Closed by samuelcolvin** 2022-07-04 19:52 UTC
Labels: bug

**Comment by Wicker25** [comment] 2022-07-04 20:25
@samuelcolvin , thank you for the help. I totally missed that one!
