### ISSUE TITLE
ValidationError for Schema use in dataclass

### ISSUE THREAD

**Issue by Midnighter** [samuelcolvin/pydantic#493] opened 2019-04-28 14:16 UTC
# Bug

(At least I think it is a bug, maybe it's a feature.)

* OS: Linux 4.15.0-48-generic x86_64
* Python version: Python 3.7.0
* Pydantic version: 0.24

I'm trying to define a pydantic dataclass model that renders nicely to a JSON schema with title, description, etc.

```py
import pydantic
from pydantic.dataclasses import dataclass

@dataclass
class Foo:
    number: pydantic.confloat(ge=0.0, le=10.0) = pydantic.Schema(default=5.0, title="Magic Number")
```

I would have expected the above to work but it raises a validation error:

```py
>>> Foo()
ValidationError: 1 validation error
number
  value is not a valid float (type=type_error.float)
```

Assigning a float works just fine:

```py
>>> Foo(number=6.0)
Foo(number=6.0)
```

Some observations:

1. Using `BaseModel` instead of a dataclass works just fine.
2. Using just the value as default instead of `Schema` also works.
    ```py
    @dataclass
    class Foo:
        number: pydantic.confloat(ge=0.0, le=10.0) = 5.0
    ```
3. What I tried at first seems to me the most concise to me but I can replicate that behavior using a config class and that works.

```py
class Config:
    fields = {"number": {"title": "Magic Number"}}

@dataclass(config=Config)
class Foo:
    number: pydantic.confloat(ge=0.0, le=10.0) = 5.0
```

So the last option works for me but I was wondering if what I had originally written is intended to work also.

---

Looking some more into it, this is covered by #470. Can you give some pointers on how to tackle this issue to make this behavior possible?

**Comment by samuelcolvin** [comment] 2019-04-28 14:53
Yes bug, thanks for reporting. I haven't looking into it, but shouldn't be too hard to fix. 

PR welcome our I'll look at it when I get a chance.

**Comment by samuelcolvin** [comment] 2019-10-17 14:13
duplicate of #470

**Closed by samuelcolvin** 2019-10-17 14:13 UTC
Labels: Schema, duplicate, feature request
