### ISSUE TITLE
Subclasses of known types are not JSON serializable

### ISSUE THREAD

**Issue by StephenBrown2** [samuelcolvin/pydantic#1281] opened 2020-03-02 17:22 UTC
# Feature Request/(Bug?)

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
        pydantic version: 1.4
       pydantic compiled: False
            install path: /Users/step7212/.pyenv/versions/3.8.1/envs/fastdate/lib/python3.8/site-packages/pydantic
          python version: 3.8.1 (default, Jan 10 2020, 09:36:37)  [Clang 11.0.0 (clang-1100.0.33.16)]
                platform: macOS-10.14.6-x86_64-i386-64bit
optional deps. installed: []
```

I would like to use a package that subclasses a standard python library class, adding convenience features but maintaining the interface of it's inheritance. Currently, pydantic will error when attempting to serialize the subclass, as it is not known in `ENCODERS_BY_TYPE`: https://github.com/samuelcolvin/pydantic/blob/e3243d267b06bda2d7b2213a8bad70f82171033c/pydantic/json.py#L20-L40

Example:
```py
>>> import pendulum
>>> import pydantic

>>> class MyModel(pydantic.BaseModel):
...     date_field: pendulum.DateTime
... 
>>> m = MyModel(date_field=pendulum.now('UTC'))
>>> m
MyModel(date_field=DateTime(2020, 3, 2, 16, 44, 42, 977836, tzinfo=Timezone('UTC')))
>>> m.dict()
{'date_field': DateTime(2020, 3, 2, 16, 44, 42, 977836, tzinfo=Timezone('UTC'))}
>>> m.json()
Traceback (most recent call last):
  File "/Users/step7212/git/hub/pydantic/pydantic/json.py", line 57, in pydantic_encoder
    encoder = ENCODERS_BY_TYPE[type(obj)]
KeyError: <class 'pendulum.datetime.DateTime'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/step7212/git/hub/pydantic/pydantic/main.py", line 419, in json
    return self.__config__.json_dumps(data, default=encoder, **dumps_kwargs)
  File "/Users/step7212/.pyenv/versions/3.8.1/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/Users/step7212/.pyenv/versions/3.8.1/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Users/step7212/.pyenv/versions/3.8.1/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/step7212/git/hub/pydantic/pydantic/json.py", line 59, in pydantic_encoder
    raise TypeError(f"Object of type '{obj.__class__.__name__}' is not JSON serializable")
TypeError: Object of type 'DateTime' is not JSON serializable
```

Since all pendulum types are children of the std `datetime` types, they should be serializable in the same way:
```py
>>> import pendulum
>>> import pydantic
>>> 
>>> class MyModel(pydantic.BaseModel):
...     date_field: pendulum.DateTime
... 
>>> m = MyModel(date_field=pendulum.now('UTC'))
>>> m
MyModel(date_field=DateTime(2020, 3, 2, 16, 42, 22, 403965, tzinfo=Timezone('UTC')))
>>> m.dict()
{'date_field': DateTime(2020, 3, 2, 16, 42, 22, 403965, tzinfo=Timezone('UTC'))}
>>> m.json()
'{"date_field": "2020-03-02T16:42:22.403965+00:00"}'
```
This is doable by iterating over the [method resolution order](https://docs.python.org/3/library/stdtypes.html#class.__mro__) attribute, and I've created a branch to demonstrate, which was used for the desired output above: https://github.com/samuelcolvin/pydantic/compare/master...StephenBrown2:encode_known_subclasses
<details>
<summary>Benchmarks for funsies, this actually turns out to be a little faster than before:</summary>

```
❯ git checkout master
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
❯ make benchmark-pydantic
python benchmarks/run.py pydantic-only
generating test cases...
    pydantic time=1.043s, success=50.10%
    pydantic time=0.982s, success=50.10%
    pydantic time=0.788s, success=50.10%
    pydantic time=0.732s, success=50.10%
    pydantic time=0.741s, success=50.10%
    pydantic best=0.732s, avg=0.857s, stdev=0.145s

    pydantic best=121.947μs/iter avg=142.857μs/iter stdev=24.164μs/iter version=1.4a1
❯ git checkout encode_known_subclasses
Switched to branch 'encode_known_subclasses'
Your branch is up to date with 'mine/encode_known_subclasses'.
❯ make benchmark-pydantic
python benchmarks/run.py pydantic-only
    pydantic time=0.973s, success=50.10%
    pydantic time=0.742s, success=50.10%
    pydantic time=0.731s, success=50.10%
    pydantic time=0.764s, success=50.10%
    pydantic time=0.734s, success=50.10%
    pydantic best=0.731s, avg=0.789s, stdev=0.104s

    pydantic best=121.800μs/iter avg=131.485μs/iter stdev=17.306μs/iter version=1.4a1
```

Perhaps this could also encourage the merge of using the `__class__` attribute instead of `type()` as well: https://github.com/samuelcolvin/pydantic/compare/samuelcolvin:master...use-class-attribute EDITED Rebased on current master: https://github.com/samuelcolvin/pydantic/compare/master...StephenBrown2:use-class-attribute

</details>

<details>
<summary>Aside on usage of __mro__:</summary>

I noticed that [`__mro__`](https://docs.python.org/3/library/stdtypes.html?highlight=__mro__#class.__mro__) is not used in many places, though it is referenced in a few places, mostly in mypy.py:

https://github.com/samuelcolvin/pydantic/blob/e3243d267b06bda2d7b2213a8bad70f82171033c/pydantic/class_validators.py#L331-L332
https://github.com/samuelcolvin/pydantic/blob/e3243d267b06bda2d7b2213a8bad70f82171033c/pydantic/main.py#L153
https://github.com/samuelcolvin/pydantic/blob/e3243d267b06bda2d7b2213a8bad70f82171033c/pydantic/mypy.py#L84
https://github.com/samuelcolvin/pydantic/blob/e3243d267b06bda2d7b2213a8bad70f82171033c/pydantic/mypy.py#L174
https://github.com/samuelcolvin/pydantic/blob/e3243d267b06bda2d7b2213a8bad70f82171033c/pydantic/mypy.py#L204
https://github.com/samuelcolvin/pydantic/blob/e3243d267b06bda2d7b2213a8bad70f82171033c/pydantic/mypy.py#L275

Rather, [typing's `__supertype__`](https://github.com/python/cpython/blob/ab6423fe2de0ed5f8a0dc86a9c7070229326b0f0/Lib/typing.py#L1929) is used, which I assumed was custom only because I couldn't find it in the [Python docs](https://docs.python.org/3/search.html?q=__supertype__) or anywhere outside of https://github.com/samuelcolvin/pydantic/blob/e3243d267b06bda2d7b2213a8bad70f82171033c/pydantic/typing.py#L180-L187

Would it be prudent/performant to replace the usage of `__supertype__` with a fast-breaking iteration of `__mro__` or perhaps more common usage of `lenient_subclass` in `typing.py`? and subsequently:
https://github.com/samuelcolvin/pydantic/blob/e3243d267b06bda2d7b2213a8bad70f82171033c/pydantic/fields.py#L361-L362
https://github.com/samuelcolvin/pydantic/blob/e3243d267b06bda2d7b2213a8bad70f82171033c/pydantic/schema.py#L641-L642
In particular, other checks for inheritance:
https://github.com/samuelcolvin/pydantic/blob/e3243d267b06bda2d7b2213a8bad70f82171033c/pydantic/validators.py#L554-L565
https://github.com/samuelcolvin/pydantic/blob/e3243d267b06bda2d7b2213a8bad70f82171033c/pydantic/utils.py#L103-L104
and of course, the tests:
https://github.com/samuelcolvin/pydantic/blob/e3243d267b06bda2d7b2213a8bad70f82171033c/tests/test_utils.py#L141-L153

</details>

**Comment by samuelcolvin** [comment] 2020-03-06 13:00
This is really a duplicate of #1157, see the discussion there.

**Comment by samuelcolvin** [comment] 2020-03-06 13:06
If you have suggestions on `__mro__` please create another issue, but from memory there wasn't another option than `__supertype__`.

**Closed** 2020-04-18 16:11 UTC
Labels: duplicate, feature request
