### ISSUE TITLE
AssertionError in `pydantic.fields.Field._populate_sub_fields`

### ISSUE THREAD

**Issue by pawelswiecki** [samuelcolvin/pydantic#197] opened 2018-06-11 10:39 UTC
`Python 3.6.5`, `pydantic==0.9.1`

```python
from typing import Tuple, Optional
from pydantic import BaseModel


class User(BaseModel):
    id: Optional[Tuple[int]]

external_data = {'id': tuple()}
user = User(**external_data)
```
now:

```bash
$ python f.py 
Traceback (most recent call last):
  File "f.py", line 5, in <module>
    class User(BaseModel):
  File "/home/pawel/.local/share/virtualenvs/acm-KRaTTq-4/lib/python3.6/site-packages/pydantic/main.py", line 116, in __new__
    config=config,
  File "/home/pawel/.local/share/virtualenvs/acm-KRaTTq-4/lib/python3.6/site-packages/pydantic/fields.py", line 84, in infer
    description=field_config and field_config.get('description'),
  File "/home/pawel/.local/share/virtualenvs/acm-KRaTTq-4/lib/python3.6/site-packages/pydantic/fields.py", line 70, in __init__
    self.prepare()
  File "/home/pawel/.local/share/virtualenvs/acm-KRaTTq-4/lib/python3.6/site-packages/pydantic/fields.py", line 112, in prepare
    self._populate_sub_fields()
  File "/home/pawel/.local/share/virtualenvs/acm-KRaTTq-4/lib/python3.6/site-packages/pydantic/fields.py", line 153, in _populate_sub_fields
    ) for t in types_]
  File "/home/pawel/.local/share/virtualenvs/acm-KRaTTq-4/lib/python3.6/site-packages/pydantic/fields.py", line 153, in <listcomp>
    ) for t in types_]
  File "/home/pawel/.local/share/virtualenvs/acm-KRaTTq-4/lib/python3.6/site-packages/pydantic/fields.py", line 70, in __init__
    self.prepare()
  File "/home/pawel/.local/share/virtualenvs/acm-KRaTTq-4/lib/python3.6/site-packages/pydantic/fields.py", line 112, in prepare
    self._populate_sub_fields()
  File "/home/pawel/.local/share/virtualenvs/acm-KRaTTq-4/lib/python3.6/site-packages/pydantic/fields.py", line 161, in _populate_sub_fields
    assert issubclass(origin, Mapping)
AssertionError
```

**Comment by samuelcolvin** [comment] 2018-06-11 10:41
duplicate of #12, tuples are not yet supported.

**Closed by samuelcolvin** 2018-06-11 10:41 UTC

**Comment by pawelswiecki** [comment] 2018-06-11 10:42
Oh, sorry. Thanks for quick reply :)
