### ISSUE TITLE
Updated enum errors().ctx to include value

### ISSUE THREAD

**Issue by BCarley** [samuelcolvin/pydantic#1601] opened 2020-06-04 11:55 UTC
# Feature Request

Currently the field `enum_values` is being included with a `type_error.enum` in  `ctx`. Are there any objections to also including the value as `value` in `ctx`?

This will make it easier to display what has tripped up the parser. If you are happy with this I'll submit a pull request.

```py
def test_enum_fails():
    with pytest.raises(ValueError) as exc_info:
        CookingModel(tool=3)
    assert exc_info.value.errors() == [
        {
            'loc': ('tool',),
            'msg': 'value is not a valid enumeration member; permitted: 1, 2',
            'type': 'type_error.enum',
            'ctx': {'value':3, 'enum_values': [ToolEnum.spanner, ToolEnum.wrench]},
        }
    ]
    assert len(exc_info.value.json()) == 235
```

This is an extension of #671

**Comment by samuelcolvin** [comment] 2020-06-04 14:23
Duplicate of #784, eventually we'll add value to all error contexts, bit wet shouldn't do it in a backwards incompatible way.

**Closed by samuelcolvin** 2020-06-04 14:23 UTC
Labels: feature request
