### ISSUE TITLE
[Question] Can pydantic peek into JSON and choose class to instantiate?

### ISSUE THREAD

**Issue by space88man** [samuelcolvin/pydantic#1539] opened 2020-05-20 15:28 UTC
# Question
Can pydantic peek into the JSON and choose the type to instantiate from a set of types?

## Background
I am creating an API but unfortunately the requests all target the same endpoint (not under my control) and use a flat JSON body consisting of varying fields where only three are common to all
request bodies.

```
# Examples of varying request bodies
# Fields: event, sessionId, timestamp are common to all request JSON, but the rest of 
# the fields are "event" dependent

## class Event
{  "event": "sessionCreated",
    "timestamp": ...
    "sessionId"" ...
}

## class SessionDestroyedEvent(Event)
{  "event": sessionDestroyed",
    "timestamp": ...
    "sessionId"" ...
    "startTime":....
    "duration": ....
    "reason":....
}

## class UserJoinedEvent(Event)
{ "event": "userJoined",
  "timestamp":...
   "sessionId":...
   "username": ...
   "location":
  "platform":...
}

## class UserLeftEvent(Event)
{ "event": "userLeft",
  "timestamp":...
   "sessionId":...
   "username": ...
   "location":
    "startTime":....
    "duration": ....
}
 ```  
Can I annotate a related  set of BaseModel (maybe all descended from a Event class) and some how get pydantic to disambiguate based on the "event" field.

```
            pydantic version: 1.5.1
            pydantic compiled: True
                 install path: /home/miniconda3/envs/venv38/lib/python3.8/site-packages/pydantic
               python version: 3.8.2 (default, Mar 26 2020, 15:53:00)  [GCC 7.3.0]
                     platform: Linux-4.18.0-147.8.1.el8_1.x86_64-x86_64-with-glibc2.10
     optional deps. installed: []

...

**Comment by StephenBrown2** [comment] 2020-05-21 20:30
There has already been quite some discussion on discriminated unions just like what you're describing here: https://github.com/samuelcolvin/pydantic/issues/619

Through a related issue, @samuelcolvin shared how he's currently managing such a response with this model: [em2/protocol/views/main.py](https://github.com/samuelcolvin/em2/blob/eaf8604cd842f4b9ed0de349fe361ca9ef9fbfbd/em2/protocol/views/main.py#L126-L170)

As to the Models used to represent the examples you've given, here's how I would construct them, which should allow you to mimic the above example in your own codebase:

```py
from enum import Enum, unique

@unique
class EventTypes(str, Enum):
    session_created = "sessionCreated"
    session_destroyed = "sessionDestroyed"
    user_joined = "userJoined"
    user_left = "userLeft"

class Event(BaseModel):
    event: EventTypes
    timestamp: datetime
    sessionId: str

class SessionDestroyedEvent(Event):
    startTime: datetime
    duration: timedelta
    reason: str

class UserEvent(Event):
    username: str
    location: str

class UserJoinedEvent(UserEvent):
    platform: str

class UserLeftEvent(UserEvent)
    startTime: datetime
    duration: timedelta
```

I'll close this issue as a duplicate of #619 , if you have any further questions, do follow that issue and ask them there.

**Closed by StephenBrown2** 2020-05-21 20:30 UTC
Labels: question
