### ISSUE TITLE
Json field causes many unwanted type warnings in Pycharm

### ISSUE THREAD

**Issue by ChongYunPeng** [samuelcolvin/pydantic#1634] opened 2020-06-15 15:07 UTC
# Question

I was trying to use the Json field type and the IDE has been giving unwanted warnings. I wonder if this behavior is expected, and if there is any workaround other than suppressing the warning?
```python
from typing import List
from pydantic import BaseModel, Json


class ComplexJsonModel(BaseModel):
    json_obj: Json[List[int]]


model = ComplexJsonModel(json_obj='[1, 2, 3]')       # Warning: Expected type 'Json[List[int]]', got 'str' instead 
for item in model.json_obj:                          # Warning: Expected 'collections.Iterable', got 'Json[List[int]]' instead 
    print(item)
```

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
pydantic version: 1.5.1
pydantic compiled: True
install path: $HOME/.pyenv/versions/3.8.0/envs/<ENV>/lib/python3.8/site-packages/pydantic
python version: 3.8.0 (default, Apr  9 2020, 17:26:00)  [Clang 11.0.3 (clang-1103.0.32.29)]
platform: macOS-10.15.3-x86_64-i386-64bit
optional deps. installed: []
```

I also have pydantic Pycharm plugin installed.

**Comment by ChongYunPeng** [comment] 2020-06-15 15:38
Deactivating and then reactivating my pydantic Pycharm plugin fixed this issue.

**Comment by samuelcolvin** [comment] 2020-06-16 11:54
wrong repo and duplicate of https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/36

**Closed by samuelcolvin** 2020-06-16 11:54 UTC
Labels: question
