### ISSUE TITLE
Untie a field type and required attrib

### ISSUE THREAD

**Issue by mrkovalchuk** [samuelcolvin/pydantic#1444] opened 2020-04-27 10:04 UTC
# Feature Request

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
 pydantic version: 1.5.1
            pydantic compiled: False
                 install path: /Users/user/projects/pydantic/pydantic
               python version: 3.7.6 (default, Dec 30 2019, 19:38:26)  [Clang 11.0.0 (clang-1100.0.33.16)]
                     platform: Darwin-19.4.0-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions', 'email-validator', 'devtools']
```

In this moment field "required" attribute is tied on two field parameters: field type and default value. 

For example:
```py
class SomeClass(BaseModel):
    a: Optional[int]
    b: Optional[int] = ...
    c: int = None   
    d: int = ...
```
a - not required
b - required
c - not required
d - required

First point. Using `Ellipsis` by default for set `required=True` on a field is not transparent.
Second point. `allow_none` attribute. What with him? 
a - allow_none
b - allow_none
c - allow_none
d - not allow_none

In my current project I have the goal: make "not required" and "not allow_none" field.
I can't see opportunity for making this kind of field. For what I need this field? PATCH queries. Some attributes can be None, but only if they define directly in query body. If not - do not make them None by default. 

I think, problem in the dependence between Type/required/allow_none attributes. 

What if we untie this dependency? May be field Type should not affect to "required"? I create PR (unfinished) for demonstrating my thought. Main points this PR:
- Management on a required attribute through config;
- "default" value can affect on a required attribute: defined -> required=None (if don't say opposite in config);
- a field Type can't affect "required";

Yes. This way makes base model definition little complex. But it's price for more transparent and independence with type and defaults (partial from last). 

What are you thinking about it? 

P.S. I didn't make test for PR, but Pydantic tests was adapted. 
In this moment field "required" attribute is tied on two field parameters: field type and default value.

**Comment by samuelcolvin** [comment] 2020-04-30 18:02
duplicate of #990. This will change in v2.

If you don't like `Ellipsis` you can use `Required`

```py
from pydantic import BaseModel, Required

class SomeClass(BaseModel):
    a: int = 4
    b: int = Required
```

**Closed by samuelcolvin** 2020-04-30 18:02 UTC
Labels: feature request

**Comment by mrkovalchuk** [comment] 2020-05-07 13:49
@samuelcolvin I think, it's not a duplicate #990 issue.

I talking about _unrequired_ + _not_none_ combination and untie _Type_ and _Required_ field attributes. In #990 talking about new type for _required_ + _none_ field attributes combination, or some tie with default value. 

Also, not that one is messages in #990 didn't give _unrequired_ + _not_none_ combination.
 
Please correct me, if exsit way to define unrequired, not_none field without default value (with #990 or without).
