### ISSUE TITLE
Ability to include private or "_" fields as part of the model.

### ISSUE THREAD

**Issue by mdgilene** [samuelcolvin/pydantic#1388] opened 2020-04-13 21:32 UTC
# Feature Request

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.4
            pydantic compiled: False
                 install path: C:\Anaconda3_2019.10\envs\test-env\Lib\site-packages\pydantic
               python version: 3.6.8 |Anaconda, Inc.| (default, Feb 21 2019, 18:30:04) [MSC v.1916 64 bit (AMD64)]
                     platform: Windows-10-10.0.17134-SP0
     optional deps. installed: ['email-validator']
```

When building models that are meant to add typing and validation to 3rd part APIs (in this case Elasticsearch) sometimes field names are prefixed with `_` however these are not private fields that should be ignored and users may want them included in the model.

```py
from pydantic import BaseModel

class ElastisearchRequest(BaseModel):
    _source: dict = Field(...)
    
    class Config:
        include_private_fields = True

request = ElasticsearchRequest(_source={'include': ['text']})

print(request.dict())
```
Output:
```json
{
  "_source": {
    "include": ["text"]
  }
}
```

**Comment by samuelcolvin** [comment] 2020-04-13 21:49
Duplicate of #655.

**Closed by samuelcolvin** 2020-04-13 21:49 UTC
Labels: feature request

**Comment by StephenBrown2** [comment] 2020-04-13 21:52
With MongoDB, which has an `_id` field, I usually just alias it, like:
```py
from pydantic import BaseModel, Field

class MongoResponse(BaseModel):
    id: str = Field(..., alias="_id")
    
    class Config:
        allow_population_by_field_name = True

response = MongoResponse(_id="ThisIsAnId")

print(response.dict())
```
Output:
```
{'id': 'ThisIsAnId'}
```

So with your example:
```py
from pydantic import BaseModel, Field

class ElasticsearchRequest(BaseModel):
    source: dict = Field(..., alias="_source")

    class Config:
        allow_population_by_field_name = True

request = ElasticsearchRequest(_source={'include': ['text']})

print(request.dict())
print(request.dict(by_alias=True))
```
Output:
```
{'source': {'include': ['text']}}
{'_source': {'include': ['text']}}
```

**Comment by rafa-acioly** [comment] 2020-08-12 19:51
@StephenBrown2 how can i use the `_id` as `non-required` using `alias`? because the `_id` is only generated once have inserted a document on my collection, using your example we cannot instantiate a new class without the `_id` attribute.

**Comment by StephenBrown2** [comment] 2020-08-12 20:33
Instead of using `...` as the default, use `None`:
```py
id: str = Field(None, alias="_id")
```
