### ISSUE TITLE
Recursive models with Union and Optional

### ISSUE THREAD

**Issue by benfasoli** [samuelcolvin/pydantic#1362] opened 2020-04-03 18:04 UTC
# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.4
            pydantic compiled: False
                 install path: .../env/lib/python3.7/site-packages/pydantic
               python version: 3.7.7 (default, Mar 10 2020, 15:43:33)  [Clang 11.0.0 (clang-1100.0.33.17)]
                     platform: Darwin-19.4.0-x86_64-i386-64bit
     optional deps. installed: []
```

Recursive models can resolve to the incorrect type when `Optional` is used to define the possible sub-model types. It seems that the first possible class is chosen from the `Union` options.

I think the expected behavior is to first attempt to infer the sub-model type by comparing its class against the list of options before falling back to testing other possibilities.

```py
from typing import Optional, Union
from pydantic import BaseModel


class ModelWithX(BaseModel):
    x: Optional[int]


class ModelWithY(BaseModel):
    y: int


class RecursiveModel(BaseModel):
    model: Union[ModelWithX, ModelWithY]


RecursiveModel(model=ModelWithX(x=1))
# expects: RecursiveModel(model=ModelWithX(x=1))
# returns: RecursiveModel(model=ModelWithX(x=1)), correct


RecursiveModel(model=ModelWithY(y=1))
# expects: RecursiveModel(model=ModelWithY(y=1))
# returns: RecursiveModel(model=ModelWithX(x=None)), incorrect

```

Thoughts? #1341

**Comment by samuelcolvin** [comment] 2020-04-03 18:08
duplicate of many other issues, will be resolved by #619

**Closed by samuelcolvin** 2020-04-03 18:08 UTC
Labels: bug
