### ISSUE TITLE
Dataclasses with FrozenSet members fail upon declaration.

### ISSUE THREAD

**Issue by djpetti** [samuelcolvin/pydantic#745] opened 2019-08-13 13:47 UTC
# Feature Request

Please complete:
* OS: Ubuntu 16.04
* Python version `import sys; print(sys.version)`: 3.7.3
* Pydantic version `import pydantic; print(pydantic.VERSION)`: 0.32.1

When creating a pydantic dataclass that has a `FrozenSet` member, initialization fails in the `@dataclass` decorator.

For example,

```py
from typing import FrozenSet

from pydantic.dataclasses import dataclass

@dataclass
class MyDataClass:
    foo: FrozenSet[str]
...
```

will fail with an assertion error:

```py
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "pydantic/dataclasses.py", line 125, in pydantic.dataclasses.dataclass.wrap
  File "pydantic/dataclasses.py", line 87, in pydantic.dataclasses._process_class
  File "pydantic/main.py", line 710, in pydantic.main.create_model
  File "pydantic/main.py", line 228, in pydantic.main.MetaModel.__new__
  File "pydantic/fields.py", line 145, in pydantic.fields.Field.infer
  File "pydantic/fields.py", line 122, in pydantic.fields.Field.__init__
  File "pydantic/fields.py", line 187, in pydantic.fields.Field.prepare
  File "pydantic/fields.py", line 252, in pydantic.fields.Field._populate_sub_fields
AssertionError
```

Looking in the `pydantic` source code, it looks like this has to do with how it determines the type of the field. Specifically, the issue is that `FrozenSet`, somewhat counter-intuitively, does not appear to be a subtype of `Set`:

```py
>>> from typing import FrozenSet, Set
>>> issubclass(FrozenSet, Set)
False 
```

It looks like this if-else block has to be amended with a specific case for `FrozenSet`.

**Comment by samuelcolvin** [comment] 2019-08-13 14:24
This is not a bug, but a feature request to support the typing type `FrozenSet` which I'd be happy to do. It should accept or convert iterables to `frozenset` not `set`.

We should also improve the error handling to explain what's going on.

`FrozenSet` won't be a subtype of `set` since it's a typing object and as an object doesn't behave anything like a set. Same as `List` isn't a subtype of `list`.

PR welcome, but probably won't be merged until v1.1.

**Closed** 2019-08-21 12:13 UTC
Labels: feature request, help wanted
