### ISSUE TITLE
mypy plugin reports error on class definition line, not on exact error line

### ISSUE THREAD

**Issue by and-semakin** [samuelcolvin/pydantic#1257] opened 2020-02-25 16:06 UTC
# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.4
            pydantic compiled: False
                 install path: /Users/andreisemakin/.local/share/virtualenvs/popapi-7C7w-VGz/lib/python3.7/site-packages/pydantic
               python version: 3.7.6 (default, Dec 30 2019, 19:38:26)  [Clang 11.0.0 (clang-1100.0.33.16)]
                     platform: Darwin-19.3.0-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

```py
from pydantic import BaseModel, Field

class RecordModel(BaseModel):  # <- error is raised here
    key: str
    record_key: str = Field(..., alias="key")  # <- and not here as I expected
```

mypy check:
```
$ mypy file.py
Loading .env environment variables…
file.py:3: error: Name 'key' already defined (possibly by an import)
```

My `setup.cfg` config:
```
[mypy]
plugins = pydantic.mypy
namespace_packages = True
ignore_missing_imports = True

[pydantic-mypy]
init_forbid_extra = True
init_typed = True
warn_required_dynamic_aliases = True
warn_untyped_fields = True
```

I know that my code is wrong and I probably shouldn't do this, but I have to to keep compatibility.
I can just put `# type: ignore` on the class definition line, but this way I can miss extra errors that  I would like to see. I would prefer to put `# type: ignore` exactly on the line with error.

**Comment by samuelcolvin** [comment] 2020-03-01 12:11
PR welcome to fix this, no idea how difficult it would be.

**Comment by dmontagu** [comment] 2020-03-04 02:09
I'm confused by this example -- what does this implementation even accomplish? Is the same value getting stored in multiple fields? Could this not be implemented via a property rather than an alias?

----

Regarding the mypy issue, it looks like if you use
```python
from pydantic import BaseModel, Field


class RecordModel(BaseModel):  # <- error is raised here
    key: str
    key: str
```
mypy raises two errors -- one on the line for the class, and one on the line for the second definition. My guess is the problem is that we aren't explicitly testing for a conflict with the alias, and could be.

Given the error message is fairly unambiguous I think fixing this is a relatively low priority, but if someone else wanted to I'd be happy to review a PR to the mypy plugin.

**Comment by samuelcolvin** [comment] 2020-03-04 16:23
closing for tidiness, but happy to accept a PR if someone really cases

**Closed by samuelcolvin** 2020-03-04 16:23 UTC
Labels: bug
