### ISSUE TITLE
 TypeError: issubclass() arg 1 must be a class

### ISSUE THREAD

**Issue by DrPyser** [samuelcolvin/pydantic#545] opened 2019-05-24 22:38 UTC
# Bug

Hi. I'm getting a type error when trying to generate a schema, using fastapi:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/uvicorn/protocols/http/httptools_impl.py", line 368, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.7/site-packages/starlette/applications.py", line 133, in __call__
    await self.error_middleware(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/errors.py", line 122, in __call__
    raise exc from None
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/errors.py", line 100, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/cors.py", line 76, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/exceptions.py", line 73, in __call__
    raise exc from None
  File "/usr/local/lib/python3.7/site-packages/starlette/exceptions.py", line 62, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 585, in __call__
    await route(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 207, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 40, in app
    response = await func(request)
  File "/usr/local/lib/python3.7/site-packages/fastapi/applications.py", line 90, in openapi
    return JSONResponse(self.openapi())
  File "/usr/local/lib/python3.7/site-packages/fastapi/applications.py", line 82, in openapi
    openapi_prefix=self.openapi_prefix,
  File "/usr/local/lib/python3.7/site-packages/fastapi/openapi/utils.py", line 248, in get_openapi
    flat_models=flat_models, model_name_map=model_name_map
  File "/usr/local/lib/python3.7/site-packages/fastapi/utils.py", line 42, in get_model_definitions
    model, model_name_map=model_name_map, ref_prefix=REF_PREFIX
  File "/usr/local/lib/python3.7/site-packages/pydantic/schema.py", line 511, in model_process_schema
    model, by_alias=by_alias, model_name_map=model_name_map, ref_prefix=ref_prefix
  File "/usr/local/lib/python3.7/site-packages/pydantic/schema.py", line 537, in model_type_schema
    f, by_alias=by_alias, model_name_map=model_name_map, ref_prefix=ref_prefix
  File "/usr/local/lib/python3.7/site-packages/pydantic/schema.py", line 274, in field_schema
    ref_prefix=ref_prefix,
  File "/usr/local/lib/python3.7/site-packages/pydantic/schema.py", line 486, in field_type_schema
    ref_prefix=ref_prefix,
  File "/usr/local/lib/python3.7/site-packages/pydantic/schema.py", line 687, in field_singleton_schema
    if issubclass(field.type_, Enum):
TypeError: issubclass() arg 1 must be a class

```

For bugs/questions:
* OS: `uname -a 
Linux char-lang-dev 4.18.0-20-generic #21~18.04.1-Ubuntu SMP Wed May 8 08:43:37 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
`
* Python version `import sys; print(sys.version)`: **'3.7.1 (default, Oct 22 2018, 11:21:55) \n[GCC 8.2.0]'**
* Pydantic version `import pydantic; print(pydantic.VERSION)`: **'3.7.1 (default, Oct 22 2018, 11:21:55) \n[GCC 8.2.0]'**

Where possible please include a self contained code snippet describing your 
bug, question, or where applicable feature request:

```py
from __future__ import annotations
from typing import Optional, List

from pydantic import BaseModel, UUID4


class CategoryCreationValidator(BaseModel):
    name: str = ...
    labels: List[str] = None
    description: str = ...
    parent_id: int = None


class CategorySelectionValidator(BaseModel):
    name: str = ...
    organization_id: str = ...
    labels: Optional[str] = None
    description: str = ...
    parent_id: Optional[int] = None


class CategoryUpdateValidator(BaseModel):
    name: Optional[str] = None
    organization_id: Optional[str] = None
    labels: Optional[List[str]] = None
    description: Optional[str] = None
    parent_id: Optional[int] = None


class ClusterValidator(BaseModel):
    name: str = ...
    category_id: Optional[str] = None


class CategoryModel(BaseModel):
    id: int = ...
    name: str = ...
    description: str = ...
    parent_id: int = None
    children: List[CategoryModel]


#CategoryModel.update_forward_refs()


class ClusterModel(BaseModel):
    id: UUID4 = ...
    name: str = ...
    parent_category_id: str = ...
    queries: List[str] = ...
    urls: List[str] = ...


class SuggestionValidator(BaseModel):
    queries: List[str] = ...
    urls: List[str] = ...


class QueryCreationValidator(BaseModel):
    query_text: str = ...
    cluster_id: UUID4 = ...


class QuerySelectionValidator(BaseModel):
    cluster_id: UUID4 = ...


class UrlCreationValidator(BaseModel):
    url: str = ...
    cluster_id: UUID4 = ...


class UrlSelectionValidator(BaseModel):
    cluster_id: UUID4 = ...


class CreateClusterInput(BaseModel):
    name: str = ...
    category_id: int = ...


class ClusterSelectionValidator(BaseModel):
    category_name: str = ...

...
```

**Comment by samuelcolvin** [comment] 2019-05-25 13:42
thanks @tiangolo maybe this is as simple as using [`lenient_issubclass`](https://github.com/samuelcolvin/pydantic/blob/master/pydantic/utils.py#L231) instead of `issubclass`?

**Comment by zbarry** [comment] 2019-05-25 19:38
Coincidentally, I just came here to report an issue about the same error. In my case, it happens when you create a subclass of `BaseModel` which specifies a field of type `Dict` which does not specify mapping types, i.e.:

```python
from pydantic import BaseModel
from typing import Dict, Any

class SubclassThatWorks(BaseModel):
    asdf: int
    fdsa: Dict[Any, Any]

class SubclassThatFails(BaseModel):
    asdf: int
    fdsa: Dict
```

with the error message being:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/scratch/miniconda3/envs/jupyter/lib/python3.7/site-packages/pydantic/validators.py in find_validators(type_, arbitrary_types_allowed)
    385         try:
--> 386             if issubclass(type_, val_type):
    387                 return validators

TypeError: issubclass() arg 1 must be a class

The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)
<ipython-input-5-c7b931439a60> in <module>
----> 1 class Subclass(BaseModel):
      2     asdf: int
      3     fdsa: Dict

/scratch/miniconda3/envs/jupyter/lib/python3.7/site-packages/pydantic/main.py in __new__(mcs, name, bases, namespace)
    180                     annotation=ann_type,
    181                     class_validators=vg.get_validators(ann_name),
--> 182                     config=config,
    183                 )
    184 

/scratch/miniconda3/envs/jupyter/lib/python3.7/site-packages/pydantic/fields.py in infer(cls, name, value, annotation, class_validators, config)
    136             required=required,
    137             model_config=config,
--> 138             schema=schema,
    139         )
    140 

/scratch/miniconda3/envs/jupyter/lib/python3.7/site-packages/pydantic/fields.py in __init__(self, name, type_, class_validators, model_config, default, required, alias, schema)
    105         self.parse_json: bool = False
    106         self.shape: Shape = Shape.SINGLETON
--> 107         self.prepare()
    108 
    109     @classmethod

/scratch/miniconda3/envs/jupyter/lib/python3.7/site-packages/pydantic/fields.py in prepare(self)
    170             self.allow_none = True
    171 
--> 172         self._populate_sub_fields()
    173         self._populate_validators()
    174 

/scratch/miniconda3/envs/jupyter/lib/python3.7/site-packages/pydantic/fields.py in _populate_sub_fields(self)
    221             assert issubclass(origin, Mapping)
    222             self.key_field = self._create_sub_type(
--> 223                 self.type_.__args__[0], 'key_' + self.name, for_keys=True  # type: ignore
    224             )
    225             self.type_ = self.type_.__args__[1]  # type: ignore

/scratch/miniconda3/envs/jupyter/lib/python3.7/site-packages/pydantic/fields.py in _create_sub_type(self, type_, name, for_keys)
    235             name=name,
    236             class_validators=None if for_keys else {k: v for k, v in self.class_validators.items() if not v.whole},
--> 237             model_config=self.model_config,
    238         )
    239 

/scratch/miniconda3/envs/jupyter/lib/python3.7/site-packages/pydantic/fields.py in __init__(self, name, type_, class_validators, model_config, default, required, alias, schema)
    105         self.parse_json: bool = False
    106         self.shape: Shape = Shape.SINGLETON
--> 107         self.prepare()
    108 
    109     @classmethod

/scratch/miniconda3/envs/jupyter/lib/python3.7/site-packages/pydantic/fields.py in prepare(self)
    171 
    172         self._populate_sub_fields()
--> 173         self._populate_validators()
    174 
    175     def _populate_sub_fields(self) -> None:  # noqa: C901 (ignore complexity)

/scratch/miniconda3/envs/jupyter/lib/python3.7/site-packages/pydantic/fields.py in _populate_validators(self)
    253                     get_validators()
    254                     if get_validators
--> 255                     else find_validators(self.type_, self.model_config.arbitrary_types_allowed)
    256                 ),
    257                 self.schema is not None and self.schema.const and constant_validator,

/scratch/miniconda3/envs/jupyter/lib/python3.7/site-packages/pydantic/validators.py in find_validators(type_, arbitrary_types_allowed)
    387                 return validators
    388         except TypeError as e:
--> 389             raise RuntimeError(f'error checking inheritance of {type_!r} (type: {display_as_type(type_)})') from e
    390 
    391     if arbitrary_types_allowed:

RuntimeError: error checking inheritance of ~KT (type: KT)
```

Not sure if this is because of a design decision that `Dict` types should have the mapping types explicitly defined or not, but the error message wasn't very clear as to what the problem was.

**Comment by samuelcolvin** [comment] 2019-05-25 20:46
sounds like a different problem, could you create a new issue and perhaps even a fix?

In the meantime you should be able to use just `dict` instead of `Dict` which will have the same effect but shouldn't fail.

**Comment by DrPyser** [comment] 2019-05-27 14:38
@samuelcolvin Do you know a workaround for my situation? The doc uses `List` and `Optional` in its examples, so I'm confused on what is causing this?

**Comment by DrPyser** [comment] 2019-05-27 15:29
Ok, I can confirm the issue is the self-reference(`children: List[CategoryModel]`). Using just `list` or `List[Any]` fixes the issue.

**Comment by tiangolo** [comment] 2019-05-27 16:17
Thanks for tagging me @samuelcolvin .

I think this is then a duplicate of https://github.com/samuelcolvin/pydantic/issues/531

I still have to check/fix the JSON Schema generation when using forward refs.

For @zbarry problem, you can use `dict` or `Dict[Any, Any]`. But that's has a separate issue now.

**Comment by haizaar** [comment] 2019-06-02 04:12
Hit this one, I think, with very simple reproduction:
```python
from typing import NewType

from pydantic import BaseModel

Age = NewType("Age", int)

class Person(BaseModel):
    age: Age
```

Similar issue when generating schema in FastAPI.

So far using `class Age(int): pass` as a workaround.

**Comment by georgw777** [comment] 2019-06-04 20:26
Removing `from __future__ import annotations` fixed this issue for me. However, it would be cool if there would be support for this.

**Comment by haizaar** [comment] 2019-06-17 01:07
I don't have `from __future__ import annotations` in my code btw.

**Comment by dmontagu** [comment] 2019-06-17 04:10
@haizaar This is fixed in the current version of pydantic (v0.28), with or without the `__future__` import.

**Comment by tiangolo** [comment] 2019-06-20 21:00
@DrPyser I'm not sure what was the problem, maybe it was fixed recently in Pydantic or in FastAPI.

But here's a slightly modified (without `from __future__ import annotations`) self-contained working app:

```Python
from typing import List, Optional

from pydantic import UUID4, BaseModel

from fastapi import FastAPI


class CategoryCreationValidator(BaseModel):
    name: str = ...
    labels: List[str] = None
    description: str = ...
    parent_id: int = None


class CategorySelectionValidator(BaseModel):
    name: str = ...
    organization_id: str = ...
    labels: Optional[str] = None
    description: str = ...
    parent_id: Optional[int] = None


class CategoryUpdateValidator(BaseModel):
    name: Optional[str] = None
    organization_id: Optional[str] = None
    labels: Optional[List[str]] = None
    description: Optional[str] = None
    parent_id: Optional[int] = None


class ClusterValidator(BaseModel):
    name: str = ...
    category_id: Optional[str] = None


class CategoryModel(BaseModel):
    id: int = ...
    name: str = ...
    description: str = ...
    parent_id: int = None
    children: List["CategoryModel"]


CategoryModel.update_forward_refs()


class ClusterModel(BaseModel):
    id: UUID4 = ...
    name: str = ...
    parent_category_id: str = ...
    queries: List[str] = ...
    urls: List[str] = ...


class SuggestionValidator(BaseModel):
    queries: List[str] = ...
    urls: List[str] = ...


class QueryCreationValidator(BaseModel):
    query_text: str = ...
    cluster_id: UUID4 = ...


class QuerySelectionValidator(BaseModel):
    cluster_id: UUID4 = ...


class UrlCreationValidator(BaseModel):
    url: str = ...
    cluster_id: UUID4 = ...


class UrlSelectionValidator(BaseModel):
    cluster_id: UUID4 = ...


class CreateClusterInput(BaseModel):
    name: str = ...
    category_id: int = ...


class ClusterSelectionValidator(BaseModel):
    category_name: str = ...



app = FastAPI()


@app.post("/")
def main(
    a: CategoryCreationValidator,
    b: CategorySelectionValidator,
    c: CategoryUpdateValidator,
    d: ClusterValidator,
    e: CategoryModel,
    f: ClusterModel,
    g: SuggestionValidator,
    h: QueryCreationValidator,
    i: QuerySelectionValidator,
    j: UrlCreationValidator,
    k: UrlSelectionValidator,
    l: CreateClusterInput,
    m: ClusterSelectionValidator,
):
    return {"message": "Hello World"}
```

**Comment by DrPyser** [comment] 2019-06-21 23:24
@tiangolo Yup, I think I've tested that everything now works after updating. Thanks everyone!

**Comment by tiangolo** [comment] 2019-06-28 19:02
Great! I'll close this issue now then.

**Closed by tiangolo** 2019-06-28 19:02 UTC
Labels: bug, help wanted

**Comment by Casyfill** [comment] 2020-02-26 20:27
Having the same issue:

```
class ModelName(str, Enum):
    repeated_sale = "repeated_sale"
    main = "main"
    dummy = "dummy"


class Inference(BaseModel):
    price: int
    model: ModelName
    model_version: float
    date: date

@app.get("/infer", response_model=Inference)
def infer(
    params: dict,
    model: ModelName,
    v: Optional[float] = None,
    date: Optional["date"] = None,
) -> Inference:
    """attempts to pull predictions from snowflake"""
    result = app.model_registry.pull(model=model, v=v, date=date).predict(params)
    return {"model": model, "v": v, **result}
```

pydantic==1.4.0
fastapi==0.49.0

**Comment by dmontagu** [comment] 2020-03-04 01:58
@Casyfill I can't reproduce that error with fastapi 0.52.0 and python 3.8.

Can you try updating your fastapi version and seeing if you still have issues? If so, could you share a full self-contained example (including import statements etc.)?

**Comment by Casyfill** [comment] 2020-03-06 22:00
```
pydantic==1.4
fastapi==0.52.0
python 3.7.4
```
issue persist

**Comment by dmontagu** [comment] 2020-03-07 05:23
Could you put together a self-contained reproducible example? If you can do that I'm happy to debug/submit a PR to fix it.

**Comment by half2me** [comment] 2020-04-02 13:39
> Could you put together a self-contained reproducible example? If you can do that I'm happy to debug/submit a PR to fix it.

Here: https://github.com/samuelcolvin/pydantic/issues/1298#issuecomment-607842409

**Comment by m3xan1k** [comment] 2020-04-05 09:01
Submit same trouble as @half2me

**Comment by gronka** [comment] 2021-02-23 13:20
I'm having a similar error:

models/devices.py
------------------------------------------------------------
```
from datetime import datetime
from sqlalchemy import BigInteger, Column, Integer, String
import uuid

from . import Base

class Device(Base):
    __tablename__ = 'devices'

    #TODO: make sure String works as UUID
    hostname = Column(String(),
                      nullable=False,
                      primary_key=True,
                      default=uuid.uuid4,
                      unique=True,
                      )
    authgroup = Column(String())
    ipv4 = Column(String())
    ipv4_int = Column(Integer())
    # ipv6 is zero-padded so we don't need Integer form
    ipv6 = Column(String())
    model = Column(String())
    region = Column(String())
    serial = Column(String())
    sitename = Column(String())
    ostype = Column(String())
    version = Column(String())

    lastupdated = Column(BigInteger(),
                         nullable=False,
                         default=datetime.utcnow().timestamp(),
                         )
```


api/gql/devices_schema.py
------------------------------------------------------------
```
from typing import List

import graphene
from laceapi.models.devices import Device
from graphene_sqlalchemy import SQLAlchemyObjectType, SQLAlchemyConnectionField

class DeviceGql(SQLAlchemyObjectType):
    class Meta:
        model = Device

class Query(graphene.ObjectType):
    devices = graphene.List(DeviceGql)
    all_devices = SQLAlchemyConnectionField(DeviceGql.connection,
                                            sort=None)

    def resolve_devices(self, info):
        print('============================')
        print('resolving')
        query = DeviceGql.get_query(info)
        return query.all()
```
        

api/gql/__init__.py
------------------------------------------------------------
```
from .devices_schema import Query
import graphene
from starlette.graphql import GraphQLApp

def attach_graphql(app):
    app.add_route('/api/v1/graphql', GraphQLApp(schema=graphene.Schema(query=Query)))
```



trace: 
------------------------------------------------------------
```
WARNING:  StatReload detected file change in 'gql/devices_schema.py'. Reloading...
Configuration loaded
LACEAPI_ENV: local
LACEAPI_ROOT: /home/voider/projects/lace-api
base url: http://localhost/
Process SpawnProcess-10:
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/voider/.virtualenvs/api/lib/python3.9/site-packages/uvicorn/subprocess.py", line 61, in subprocess_started
    target(sockets=sockets)
  File "/home/voider/.virtualenvs/api/lib/python3.9/site-packages/uvicorn/server.py", line 49, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/voider/.virtualenvs/api/lib/python3.9/site-packages/uvicorn/server.py", line 56, in serve
    config.load()
  File "/home/voider/.virtualenvs/api/lib/python3.9/site-packages/uvicorn/config.py", line 308, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/voider/.virtualenvs/api/lib/python3.9/site-packages/uvicorn/importer.py", line 20, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "./asgi.py", line 3, in <module>
    app = create_app()
  File "/home/voider/projects/lace-api/src/laceapi/api/app.py", line 13, in create_app
    attach_graphql(app)
  File "/home/voider/projects/lace-api/src/laceapi/api/gql/__init__.py", line 8, in attach_graphql
    app.add_route('/api/v1/graphql', GraphQLApp(schema=graphene.Schema(query=Query)))
  File "/home/voider/.virtualenvs/api/lib/python3.9/site-packages/graphene/types/schema.py", line 78, in __init__
    self.build_typemap()
  File "/home/voider/.virtualenvs/api/lib/python3.9/site-packages/graphene/types/schema.py", line 167, in build_typemap
    self._type_map = TypeMap(
  File "/home/voider/.virtualenvs/api/lib/python3.9/site-packages/graphene/types/typemap.py", line 80, in __init__
    super(TypeMap, self).__init__(types)
  File "/home/voider/.virtualenvs/api/lib/python3.9/site-packages/graphql/type/typemap.py", line 31, in __init__
    self.update(reduce(self.reducer, types, OrderedDict()))  # type: ignore
  File "/home/voider/.virtualenvs/api/lib/python3.9/site-packages/graphene/types/typemap.py", line 88, in reducer
    return self.graphene_reducer(map, type)
  File "/home/voider/.virtualenvs/api/lib/python3.9/site-packages/graphene/types/typemap.py", line 117, in graphene_reducer
    return GraphQLTypeMap.reducer(map, internal_type)
  File "/home/voider/.virtualenvs/api/lib/python3.9/site-packages/graphql/type/typemap.py", line 109, in reducer
    field_map = type_.fields
  File "/home/voider/.virtualenvs/api/lib/python3.9/site-packages/graphql/pyutils/cached_property.py", line 22, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/voider/.virtualenvs/api/lib/python3.9/site-packages/graphql/type/definition.py", line 198, in fields
    return define_field_map(self, self._fields)
  File "/home/voider/.virtualenvs/api/lib/python3.9/site-packages/graphql/type/definition.py", line 212, in define_field_map
    field_map = field_map()
  File "/home/voider/.virtualenvs/api/lib/python3.9/site-packages/graphene/types/typemap.py", line 275, in construct_fields_for_type
    map = self.reducer(map, field.type)
  File "/home/voider/.virtualenvs/api/lib/python3.9/site-packages/graphene_sqlalchemy/fields.py", line 24, in type
    if issubclass(nullable_type, Connection):
TypeError: issubclass() arg 1 must be a class
```

**Comment by abury** [comment] 2023-05-23 07:01
Can also confirm we randomly started seeing the same issue in the past hour for what seems like no apparent reason. Code has been working for months and hasn't been touched, but our builds randomly started failing.

pydantic==1.9.0
python 3.8.16

**Comment by stazz** [comment] 2023-05-23 07:14
FWIW, also started happening here, with exactly same symptoms, and without any modifications to the code. We have Pydantic version pinned. Happens also on classes which don't self-reference themselves.

Versions: Python `3.8`, pydantic `1.10.5` (also tried `1.10.7` with same result).

**Comment by TorgeirBrenn** [comment] 2023-05-23 07:23
Same here! I have Pydantic version 1.9.2 but happened with 1.10.7 also. Strangely required a reinstall to trigger the same problem locally. I noticed the reinstall also installed the newly release typing-extensions 4.6.0. Forcing typing-extensions==4.5.0 fixed the issue for me.

To reproduce, tested with Pydantic 1.9.2 and 1.10.7:
```
from typing import Literal
from pydantic import BaseModel


class MyModel(BaseModel):
    a: Literal["b", "c"]
```
I hope this isn't as widespread as it seems at first glance.

To fix: 
Force  typing-extensions==4.5.0.

**Comment by ofiriluz** [comment] 2023-05-23 07:32
Happens similarly here, started randomly happening this morning, sadly i cannot force typing-extensions version for our project layout at the moment
Version: Python 3.8, pydantic 1.10.7

**Comment by kylian-p** [comment] 2023-05-23 10:22
Downgrading the typing-extension version to 4.5.0 working perfectly ! Thank's

**Comment by sietse** [comment] 2023-05-23 11:35
If you're stuck on `typing_extensions==4.6.0`, you can also avoid the bug by importing Literal from `typing_extensions` instead of from `typing`.

```
# Triggers bug whenever `typing.Literal is not typing_extensions.Literal`
from typing import Literal

# Avoids bug
from typing_extensions import Literal
```

**Comment by sietse** [comment] 2023-05-23 12:01
Third workaround, again if you have to stay on `type_extensions==4.6.0`: patching.

The code below is single-module, but also works for multi-module programs, as long as the patch happens before any `from typing import Literal` statements.

```
# ---- Start of patch ----
# Workaround for https://github.com/pydantic/pydantic/issues/5821
#
# Run this code once at the start of your program.
#
# It patches `typing.Literal` to refer to `typing_extensions.Literal`,
# and thereby avoids a bug in Pydantic<=1.10.7 code for is_literal_type
import typing_extensions
import typing
typing.Literal = typing_extensions.Literal  # type: ignore
# ---- End of patch ----

# ---- Your program goes here ----
from pydantic import BaseModel
from typing import Literal

class Hello(BaseModel):
    x: Literal['x']   # patch prevents error
    y: typing.Literal['y]   # patch prevents error
```

**Comment by Kilo59** [comment] 2023-06-02 13:51
This also seems to be happening for `Hashable`
```python
import pydantic
from typing import Hashable


class MyModel(pydantic.BaseModel):
   foo: Hashable

MyModel.schema()
...
File /opt/homebrew/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/abc.py:123, in ABCMeta.__subclasscheck__(cls, subclass)
    121 def __subclasscheck__(cls, subclass):
    122     """Override for issubclass(subclass, cls)."""
--> 123     return _abc_subclasscheck(cls, subclass)

TypeError: issubclass() arg 1 must be a class
```
pydantic: 1.10.7
typing_extensions: 4.5.0

**Comment by hramezani** [comment] 2023-06-02 13:52
@Kilo59 please try `pydantic 1.10.8` that contains the fix

**Comment by Karimai** [comment] 2023-06-30 18:07
class User(UserBase):
    id: int
    residences: List[Residence] = []
    # residences = []
This type hint create the following issue when I start fastapi project. If I remove that type hint, there won't be an issue.


ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/karim/.cache/pypoetry/virtualenvs/percent-lJdk6Ebz-py3.11/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karim/.cache/pypoetry/virtualenvs/percent-lJdk6Ebz-py3.11/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karim/.cache/pypoetry/virtualenvs/percent-lJdk6Ebz-py3.11/lib/python3.11/site-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "/home/karim/.cache/pypoetry/virtualenvs/percent-lJdk6Ebz-py3.11/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/karim/.cache/pypoetry/virtualenvs/percent-lJdk6Ebz-py3.11/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/karim/.cache/pypoetry/virtualenvs/percent-lJdk6Ebz-py3.11/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/karim/.cache/pypoetry/virtualenvs/percent-lJdk6Ebz-py3.11/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/karim/.cache/pypoetry/virtualenvs/percent-lJdk6Ebz-py3.11/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/karim/.cache/pypoetry/virtualenvs/percent-lJdk6Ebz-py3.11/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/karim/.cache/pypoetry/virtualenvs/percent-lJdk6Ebz-py3.11/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/karim/.cache/pypoetry/virtualenvs/percent-lJdk6Ebz-py3.11/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/karim/.cache/pypoetry/virtualenvs/percent-lJdk6Ebz-py3.11/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/karim/.cache/pypoetry/virtualenvs/percent-lJdk6Ebz-py3.11/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/home/karim/.cache/pypoetry/virtualenvs/percent-lJdk6Ebz-py3.11/lib/python3.11/site-packages/fastapi/applications.py", line 231, in openapi
    return JSONResponse(self.openapi())
                        ^^^^^^^^^^^^^^
  File "/home/karim/.cache/pypoetry/virtualenvs/percent-lJdk6Ebz-py3.11/lib/python3.11/site-packages/fastapi/applications.py", line 206, in openapi
    self.openapi_schema = get_openapi(
                          ^^^^^^^^^^^^
  File "/home/karim/.cache/pypoetry/virtualenvs/percent-lJdk6Ebz-py3.11/lib/python3.11/site-packages/fastapi/openapi/utils.py", line 423, in get_openapi
    definitions = get_model_definitions(
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karim/.cache/pypoetry/virtualenvs/percent-lJdk6Ebz-py3.11/lib/python3.11/site-packages/fastapi/utils.py", line 60, in get_model_definitions
    m_schema, m_definitions, m_nested_models = model_process_schema(
                                               ^^^^^^^^^^^^^^^^^^^^^
  File "pydantic/schema.py", line 582, in pydantic.schema.model_process_schema
  File "pydantic/schema.py", line 623, in pydantic.schema.model_type_schema
  File "pydantic/schema.py", line 256, in pydantic.schema.field_schema
  File "pydantic/schema.py", line 528, in pydantic.schema.field_type_schema
  File "pydantic/schema.py", line 927, in pydantic.schema.field_singleton_schema
  File "<frozen abc>", line 123, in __subclasscheck__
TypeError: issubclass() arg 1 must be a class

**Comment by hramezani** [comment] 2023-06-30 18:24
@Karimai update Pydantic to `1.10.10`

**Comment by freywaid** [comment] 2023-07-02 01:16
@hramezani   I'm at pydantic 1.10.10 and I see this error

**Comment by Karimai** [comment] 2023-07-02 10:05
@hramezani 
After update:
  • Updating pydantic (1.10.9 -> 1.10.10)
Still the issue exist!

@freywaid 
however, it works after adding User.update_forward_refs() at the end of the file (after implementation of all classes).

**Comment by hramezani** [comment] 2023-07-02 10:22
@Karimai @freywaid could you please provide a minimal example that reproduce the error?

**Comment by Karimai** [comment] 2023-07-02 11:00
@hramezani 
I implemented the basic tutorial [1] and changed the order of User and Item class in the schemas.py.
I added `from __future__ import annotations` 

`>>> pydantic.VERSION
'1.10.10`

The issue solved when I added `User.update_forward_refs()` after definition of Item and User class in the schemas.py

[1] https://fastapi.tiangolo.com/tutorial/sql-databases/

**Comment by hramezani** [comment] 2023-07-02 11:20
Thanks @Karimai.

Yeah, as @freywaid mentioned, `update_forward_refs` should solve the problem.

**Comment by olivarius1** [comment] 2024-06-04 02:18
I encountered this issue in my code as well. My environment includes pydantic==1.8.2 and typing-extensions==4.12.1. When I downgraded typing-extensions to 4.1.1, the error disappeared. However, what's confusing is that when I checked the dependencies using pipdeptree, the output showed typing-extensions [required: >=3.10.0 ..., so maybe there should be a restriction on the higher version.
