### ISSUE TITLE
Allow ommiting type annotation for inherited field if new default can be validated as parent's type annotation

### ISSUE THREAD

**Issue by Drino** [samuelcolvin/pydantic#1870] opened 2020-08-24 21:53 UTC
# Feature Request

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.6.1
            pydantic compiled: True
                 install path: /home/abodrov/.local/lib/python3.8/site-packages/pydantic
               python version: 3.8.2 (default, Jul 16 2020, 14:00:26)  [GCC 9.3.0]
                     platform: Linux-5.7.4-050704-generic-x86_64-with-glibc2.29
     optional deps. installed: []
```

Is there a reason it is not possible to do something like that? 
```py
from typing import Sequence

from pydantic import BaseModel

class Parent(BaseModel):
    field: Sequence[int]


class Child(Parent):
    field = (1,)
# Currently raises:
# TypeError: The type of Child.field differs from the new default value; if you wish to change the type of this field, please use a type annotation
```

**Comment by jhole89** [comment] 2020-09-03 22:32
@Drino Just stumbled across this myself. The best way I've found to get around this is to re-establish the type on the inherited class, e.g.

```
from typing import Sequence

from pydantic import BaseModel

class Parent(BaseModel):
    field: Sequence[int]


class Child(Parent):
    field: Sequence[int] = (1,)
```

While it requires some minor code duplication, it does work and kind of makes sense when over-writing a parent type.

**Comment by PrettyWood** [comment] 2021-01-03 23:06
Duplicate of #1296

**Closed by PrettyWood** 2021-01-03 23:06 UTC
Labels: feature request
