### ISSUE TITLE
How to report meningful error to user when string regex match fails?

### ISSUE THREAD

**Issue by indy-independence** [samuelcolvin/pydantic#802] opened 2019-09-10 08:59 UTC
# Question

Please complete:
* OS: linux
* Python version `import sys; print(sys.version)`: 3.7.4 (default, Jul  9 2019, 16:48:28)
* Pydantic version `import pydantic; print(pydantic.VERSION)`: 0.18

I want to report a more useful/customised message back to the user when a string regex match fails. Currently the user will get a message like: string does not match regex "^[a-zA-Z][a-zA-Z0-9-_]{0,31}$"
For someone who doesn't know regex this is not helpful, so I want to include another message. Is it possible to access the description field from the schema when catching the ValidationError and use that to pass to the user maybe? I've checked in the errors() dict but can't find anything relating to the schema that triggered the error there.

```
VLAN_NAME_REGEX = r'^[a-zA-Z][a-zA-Z0-9-_]{0,31}$'
vlan_name_schema = Schema(..., regex=VLAN_NAME_REGEX,
                          description="Max 32 alphanumeric chars, beginning with a character")

    except ValidationError as e:
        for num, error in enumerate(e.errors()):
...
```
Variables that I've found that I can use when trying to report an error to the user:
{'loc': ('vxlans', 0, 'vlan_name'), 'msg': 'string does not match regex "^[a-zA-Z][a-zA-Z0-9-_]{0,31}$"', 'type': 'value_error.str.regex', 'ctx': {'pattern': '^[a-zA-Z][a-zA-Z0-9-_]{0,31}$'}}

**Comment by samuelcolvin** [comment] 2019-10-17 14:40
duplicate of #322, basically we need to document how to implement your own error messages.

**Closed by samuelcolvin** 2019-10-17 14:40 UTC
Labels: question

**Comment by indy-independence** [comment] 2020-01-23 14:53
Yes that solves part of my problem, but I would also like to access the "description" of the Schema/Field and use that in my error message. So instead of sending the actual regex pattern as an error message, I would like to send the description "Max 32 alphanumeric chars, beginning with a character" etc
I can run .schema() on the model and then try to find the description in there by using the error['loc'] tuple maybe? But there's references as strings etc, maybe there's an easier way?

**Comment by indy-independence** [comment] 2020-01-24 12:27
I ended up with this horrible little piece of code to get the description from the field to the error message:

```
def get_pydantic_field_descr(schema: dict, loc: tuple):
    """Get the description from a pydantic Field definition based on a model
    schema and a "loc" tuple from pydantic ValidatorError.errors() """
    next_schema = None
    for loc_part in loc:
        if next_schema and '$ref' in next_schema:
            ref_to = next_schema['$ref'].split('/')[2]
            next_schema = schema['definitions'][ref_to]['properties'][loc_part]
        elif next_schema:
            if type(loc_part) == int:
                next_schema = next_schema['items']
            else:
                next_schema = schema['definitions'][next_schema]['properties'][loc_part]
        else:
            next_schema = schema['properties'][loc_part]
    if 'description' in next_schema:
        return next_schema['description']
    else:
        return None
```

There's probably a better way to do this so if anyone has any ideas I'm all ears...
