### ISSUE TITLE
Optional typecasting

### ISSUE THREAD

**Issue by Zweedeend** [samuelcolvin/pydantic#45] opened 2017-06-08 12:38 UTC
I tried out Pydantic to see if my data had the right type, but I was surprised that it cast the data to the right type. I would expect an error to be raised if the value is a list (say), instead I got the string representation of that list.  For example, I found this string validator:

```python
def str_validator(v) -> str:
    if isinstance(v, (str, NoneType)):
        return v
    elif isinstance(v, bytes):
        return v.decode()
    return str(v)  # <-- Should this raise a validation error, or cast to a string?
```

Maybe this is intended behaviour, but I think it should raise a validation error. Maybe a `strict` option can be added to the `Config` class?

**Comment by samuelcolvin** [comment] 2017-06-08 13:05
The problem is that it's fairly subjective what should be converted to a string:
* `bytes`: most people would probably say yes
* `int`: again probably yes
* `float`: a bit more dubious
* `True`, `False`: some would say no but others might want it
* list, dict, set: as you say this is probably unexpected but there are situations where it might be the easiest solution.

I'm fairly concerned about performance so I didn't want to add lots of type checks to a validator like `str_validator` which is used a lot.

That said,
```python
elif isinstance(v, (list, dict, set)):
    raise ValueError('...')
```
would seem pretty simple and probably wouldn't have a big performance impact.

The other option would be to add a validate method to your model `def validate_<field name>(self, v)`. (warning: I'm going to be changing how validators work a lot at some point, so this will probably break at some point but won't be hard to fix.)

Or create a custom type

```python
class StrictStr(str):
    @classmethod
    def get_validators(cls):
        yield cls.check_not_list
        yield str_validator
```

**Comment by samuelcolvin** [comment] 2017-06-08 13:25
Simplest option would be to add `StrictStr` to pydantic so people can use that when required. That would be explicit and require the minimum change.

**Comment by samuelcolvin** [comment] 2017-06-21 12:47
see #52. @Zweedeend I'll leave it for a few hours in case you have any feedback, then merge. If I've already merged give feedback anyway and we can continue on another PR.

**Closed** 2017-06-21 16:59 UTC
