### ISSUE TITLE
Type coercion on TypeVar fields even though type is known

### ISSUE THREAD

**Issue by tedgrav** [samuelcolvin/pydantic#1447] opened 2020-04-27 21:10 UTC
# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.3
            pydantic compiled: True
                 install path: /usr/local/lib/python3.7/site-packages/pydantic
               python version: 3.7.4 (default, Oct 17 2019, 05:59:21)  [GCC 8.3.0]
                     platform: Linux-4.15.0-96-generic-x86_64-with-debian-10.1
     optional deps. installed: ['email-validator']
```

Pydantic appears to coerce the value of a  type variable based on the order of types defined for that type variable instead of the know type of that variable. The following code exhibits the behavior: 

```py
from pydantic import BaseModel, StrictBool, StrictInt, StrictStr
from typing import TypeVar

BoolFirst = TypeVar('BoolFirst', bool, int, str)
BoolLast = TypeVar('BoolLast', int, str, bool)
StrictType = TypeVar('StrictType', StrictBool, StrictInt, StrictStr)


class TypeTest(BaseModel):
    first: BoolFirst
    last: BoolLast
    strict: StrictType


def show_type(value: BoolFirst):
    print(f"Parameter type: {type(value)} value: {value}")
    model = TypeTest(first=value, last=value, strict=value)

    print(f"First type: {type(model.first)} : value {model.first}")
    print(f"Last type: {type(model.last)} : value {model.last}")
    print(f"Strict type: {type(model.strict)} : value {model.strict}")
    print("")


[show_type(v) for v in ['true', 1, True]]

```

Output:
```
Parameter type: <class 'str'> value: true
First type: <class 'bool'> : value True
Last type: <class 'str'> : value true
Strict type: <class 'str'> : value true

Parameter type: <class 'int'> value: 1
First type: <class 'bool'> : value True
Last type: <class 'int'> : value 1
Strict type: <class 'int'> : value 1

Parameter type: <class 'bool'> value: True
First type: <class 'bool'> : value True
Last type: <class 'int'> : value 1
Strict type: <class 'bool'> : value True
```

As can be seen from the output, the type and value of the show_type parameter is known to the function. When this known type/value is provided to a pydantic model, however, that value is type coerced to a value based on the order of the generic types allowed by the type variable, as can be seen by the First type:, Last type: output where the order of types within the type variable results in a different value for the model field with the same input value. The expected behaviour would be that pydantic would accept the type of the inbound value if it was any of the accepted types of the type variable instead of selecting the first type that was successfully coerced.

Currently, a workaround to this issue is to declare the types of the type variable using the equivalent pydantic strict types which results in the correct behaviour as shown in the output.

**Comment by samuelcolvin** [comment] 2020-04-30 11:35
I think this is a duplicate of #1423, please comment there if you have feedback or suggestions on the right fix.

Hint: it's not simple given the number of contexts in which union like things are used.

**Closed by samuelcolvin** 2020-04-30 11:35 UTC
Labels: bug
