### ISSUE TITLE
TypeError when use GenericModel in python3.6

### ISSUE THREAD

**Issue by mh739025250** [samuelcolvin/pydantic#1547] opened 2020-05-22 03:12 UTC
# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.5.1
            pydantic compiled: True
                 install path: /miniconda3/envs/py36/lib/python3.6/site-packages/pydantic
               python version: 3.6.10 |Anaconda, Inc.| (default, Jan  7 2020, 21:14:29)  [GCC 7.3.0]
                     platform: Linux-4.18.0-25-generic-x86_64-with-debian-buster-sid
     optional deps. installed: ['typing-extensions']
```
Example code:

```py
from typing import TypeVar, Generic
from pydantic.generics import GenericModel

TypeX = TypeVar('TypeX')

class BaseClass(GenericModel, Generic[TypeX]):
    X: TypeX

```

the output:

```
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
```

**Comment by samuelcolvin** [comment] 2020-05-31 12:42
Due to complex internal changes in python between 3.6 and 3.7, pydantic does not support generics in 3.6.

If you look all generics tests are skipped in 3.6, this should be properly documented.

**Comment by samuelcolvin** [comment] 2020-05-31 12:45
duplicate of #1513.

**Closed** 2020-05-31 14:08 UTC
Labels: documentation, duplicate
