### ISSUE TITLE
list of python dataclass broken after upgrade to 1.9.0

### ISSUE THREAD

**Issue by mxlnk** [samuelcolvin/pydantic#3848] opened 2022-02-22 14:42 UTC
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
            pydantic version: 1.9.0
            pydantic compiled: True
                 install path: my_directory/venv/lib/python3.8/site-packages/pydantic
               python version: 3.8.6 (default, Sep  6 2021, 17:04:40)  [GCC 10.3.0]
                     platform: Linux-5.13.0-28-generic-x86_64-with-glibc2.33
     optional deps. installed: ['typing-extensions']
```

The following snippet works as expected with version 1.8.2 but errors with version 1.9.0

```py
from dataclasses import dataclass
from typing import List
import pydantic


@dataclass()
class A:
    a: int = 5


@dataclass()
class B_and_As:
    list_of_as: List[A]
    b: str = 'b'


def get_schema(json_cls: dataclass):
    as_pydantic = pydantic.dataclasses.dataclass(json_cls)
    schema = as_pydantic.__pydantic_model__.schema()
    print(schema)


get_schema(B_and_As)
```

error:
```
    schema = as_pydantic.__pydantic_model__.schema()
  File "pydantic/main.py", line 647, in pydantic.main.BaseModel.schema
  File "pydantic/schema.py", line 185, in pydantic.schema.model_schema
  File "pydantic/schema.py", line 617, in pydantic.schema.model_process_schema
  File "pydantic/schema.py", line 658, in pydantic.schema.model_type_schema
  File "pydantic/schema.py", line 258, in pydantic.schema.field_schema
  File "pydantic/schema.py", line 498, in pydantic.schema.field_type_schema
  File "pydantic/schema.py", line 848, in pydantic.schema.field_singleton_schema
  File "pydantic/schema.py", line 736, in pydantic.schema.field_singleton_sub_fields_schema
  File "pydantic/schema.py", line 563, in pydantic.schema.field_type_schema
  File "pydantic/schema.py", line 947, in pydantic.schema.field_singleton_schema
ValueError: Value not declarable with JSON Schema, field: name='_list_of_as' type=A required=True
```

on 1.8.2 it's prints as expected:
```
{'title': 'B_and_As', 'type': 'object', 'properties': {'list_of_as': {'title': 'List Of As', 'type': 'array', 'items': {'$ref': '#/definitions/A'}}, 'b': {'title': 'B', 'default': 'b', 'type': 'string'}}, 'required': ['list_of_as'], 'definitions': {'A': {'title': 'A', 'type': 'object', 'properties': {'a': {'title': 'A', 'default': 5, 'type': 'integer'}}}}}
```

Btw:
* `get_schema(A)` works in both versions
* [Discussed on stackoverflow](https://stackoverflow.com/questions/71048746/how-can-i-generate-json-schema-for-list-of-dataclass-with-pydantic)

**Comment by himbeles** [comment] 2022-02-28 19:37
Duplicate of #3658

**Comment by mxlnk** [comment] 2022-03-16 09:48
thanks, did not see that one, sorry.

This one also fixes the problem for me https://github.com/samuelcolvin/pydantic/pull/2557

**Closed** 2022-05-11 18:02 UTC
Labels: bug
