### ISSUE TITLE
BaseSettings - pylance complains about missing parameters

### ISSUE THREAD

**Issue by florian-sattler** [samuelcolvin/pydantic#3767] opened 2022-02-02 14:27 UTC
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.9.0
            pydantic compiled: True
                 install path: /home/user/repo/venv/lib/python3.10/site-packages/pydantic
               python version: 3.10.0 (default, Oct 11 2021, 05:33:59) [GCC 11.2.0]
                     platform: Linux-5.13.0-28-generic-x86_64-with-glibc2.34
     optional deps. installed: ['typing-extensions']
```

When using base settings in (even _without_ Field see #3617 #3753)

```py
from pydantic import BaseSettings


class MySettings(BaseSettings):
    option_1: str
    option_2: int

    
MySettings()
```

the resulting class expects the parameters to be provided by the program and not by the environment. Therefore Pylance seems to complain.

![image](https://user-images.githubusercontent.com/65666934/152172009-56cc134b-c9d1-496d-9ac5-8f48dcfcdebe.png)

Btw: I use the basic setting:
```json
"python.analysis.typeCheckingMode": "basic",
"python.languageServer": "Pylance",
```

The addition of parameters in BaseModel is welcome change, however I don't think the BaseSettings class should be affected as well.

**Comment by samuelcolvin** [comment] 2022-04-02 15:06
closing as a duplicate of #3767 which has more details.

**Closed by samuelcolvin** 2022-04-02 15:06 UTC
Labels: bug
