### ISSUE TITLE
Cannot create instanse of networks.AnyUrl

### ISSUE THREAD

**Issue by rappongy** [samuelcolvin/pydantic#1260] opened 2020-02-26 03:31 UTC
# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.4
            pydantic compiled: True
                 install path: /home/emil/workdir/virtualassistant/virt_assistant_indexingmodule/venv/lib/python3.7/site-packages/pydantic
               python version: 3.7.3 (default, Apr  3 2019, 19:16:38)  [GCC 8.0.1 20180414 (experimental) [trunk revision 259383]]
                     platform: Linux-5.0.0-37-generic-x86_64-with-Ubuntu-18.04-bionic
     optional deps. installed: ['typing-extensions']
```

Facing exceptions when trying to create instanse of **AnyUrl**

```py
>>>from pydantic import AnyUrl

>>>AnyUrl('http://site.com')

Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "pydantic/networks.py", line 105, in pydantic.networks.AnyUrl.__init__
TypeError: __init__() needs keyword-only argument scheme

>>>AnyUrl(url='http://site.com')

Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "pydantic/networks.py", line 105, in pydantic.networks.AnyUrl.__init__
TypeError: __init__() needs keyword-only argument scheme

```

**Comment by samuelcolvin** [comment] 2020-02-26 03:35
Duplicate of #1106

**Closed by samuelcolvin** 2020-02-26 03:35 UTC
Labels: bug
