### ISSUE TITLE
Add a standalone implementation for parse_raw similar to parse_file_as and parse_obj_as

### ISSUE THREAD

**Issue by mastern2k3** [samuelcolvin/pydantic#1812] opened 2020-08-09 14:16 UTC
# Feature Request

As described in the [docs](https://pydantic-docs.helpmanual.io/usage/models/#parsing-data-into-a-specified-type):
> Pydantic includes a standalone utility function parse_obj_as that can be used to apply the parsing logic used to populate pydantic models in a more ad-hoc way. This function behaves similarly to BaseModel.parse_obj, but works with arbitrary pydantic-compatible types.

Enabling code such as this:
```py
from typing import List

from pydantic import BaseModel, parse_obj_as

class Item(BaseModel):
    id: int
    name: str

item_data = [{'id': 1, 'name': 'My Item'}]

items = parse_obj_as(List[Item], item_data)
print(items)
#> [Item(id=1, name='My Item')]
```

This works if you have a given object () to start with, but if you have a raw string or bytes you are required to parse them first into an object.

Forcing you to write this:

```py
import json

item_data = '[{"id": 1, "name": "My Item"}]'
item_data_obj = json.loads(item_data)

items = parse_obj_as(List[Item], item_data_obj)
```

Instead, I suggest a standalone parse function, similar to `parse_obj_as` but for raw data, enabling something like this:

```py
import json

item_data = '[{"id": 1, "name": "My Item"}]'

items = parse_raw_as(List[Item], item_data)
```

**Comment by PrettyWood** [comment] 2020-08-09 17:49
Duplicate of https://github.com/samuelcolvin/pydantic/issues/1789.
Maybe we could actually add it. Very easy to add and doesn't cost much

**Closed** 2020-10-09 09:35 UTC
Labels: feature request
