### ISSUE TITLE
Last patch bump included breaking change regarding default and default_factory

### ISSUE THREAD

**Issue by shifqu** [samuelcolvin/pydantic#2785] opened 2021-05-12 12:23 UTC
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
pydantic version: 1.8.2
pydantic compiled: True
install path: /Users/username/miniconda3/envs/custom-env/lib/python3.8/site-packages/pydantic
python version: 3.8.8 (default, Apr 13 2021, 12:59:45)  [Clang 10.0.0 ]
platform: macOS-10.16-x86_64-i386-64bit
optional deps. installed: ['email-validator', 'typing-extensions']
```

# Description
The following snippet would compile without error on pydantic 1.8.1
```py
import pydantic


def my_callable():
    return 5


class Model(pydantic.BaseModel):
    field_1: int = pydantic.Field(default=..., default_factory=my_callable)

Model()
Out: Model(field_1=5)
```
But on pydantic 1.8.2 (A patch bump) the above snippet will raise an error:
```py
ValueError: cannot specify both default and default_factory
```

I am not saying I disagree with the change, but I feel like patch bumping this was not the best decision and will potentially break many systems that recreate their environment with eg `pydantic~=1.8.1` in their requirements.

**Comment by samuelcolvin** [comment] 2021-05-12 13:01
> but I feel like patch bumping this was not the best decision

1. v1.8.2 was released in a hurry for good reasons.
2. It obviously wasn't our intention to break existing behaviour in the patch, but there are were a number of fixes for v1.8 that needed to be released

It looks like this might have been caused by #2502 which @PrettyWood put on the v1.8.2 milestone for good reasons.

**Comment by shifqu** [comment] 2021-05-12 13:07
> It looks like this might have been caused by #2502  
1) This is indeed what caused it.
2) I raised this bug, just to raise awareness on the breaking change, not requesting that anything changes.
3) This is a good example of why releasing in a hurry is often not desired, even for `good reasons`.

Either way, thanks for the reply. If you feel like this issue can be closed, feel free to do so.

**Comment by shifqu** [comment] 2021-05-12 13:08
FWIW; the fix to unbreak things in projects that use Pydantic is as simple as removing the `default` keyword in the field definition.  
So the code in `description` above would look something like:
```py
import pydantic


def my_callable():
    return 5


class Model(pydantic.BaseModel):
    field_1: int = pydantic.Field(default_factory=my_callable)

Model()
Out: Model(field_1=5)
```

**Comment by PrettyWood** [comment] 2021-05-12 13:10
Sorry I'm still on holidays and could not follow the patches from my phone.
Sorry my fix broke some stuff @shifqu it was not planned. But the fix that introduced this "regression" fixed more problematic cases and I would argue that your code should have raised an error in the first place when I added `default_factory`.
Anyway sorry for the inconvenience and thanks @samuelcolvin for the work yesterday on the security patches. I will be home tonight and will get back on open PRs

**Comment by samuelcolvin** [comment] 2021-05-12 14:23
It's worth noting that the same error was raised in previous versions of pydantic if you set the default value to anything other than `...`, e.g. explicitly setting `Field(..., default_factory=my_callable)` now causes an error where it didn't used to, `Field(4, default_factory=my_callable)` always caused an error.

Without `default_factory`, `Field(...)` is the same as `Field()`, so it should be fairly rare that people used `Field(..., default_factory=my_callable)`

But thanks for reporting @shifqu in case anyone else finds this.

**Closed by samuelcolvin** 2021-05-12 14:23 UTC
Labels: bug
