### ISSUE TITLE
Pydantic fails with Python 3.10 new UnionType

### ISSUE THREAD

**Issue by DrJackilD** [samuelcolvin/pydantic#3300] opened 2021-10-07 20:35 UTC
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug
Pydantic fails with a new-style unios, presented in Python 3.10. The reason is straightforward - it simply doesn't know about [UnionType](https://docs.python.org/3/library/types.html?highlight=uniontype#types.UnionType). 

The problem is here: `pydantic.fields.py:529` where we check the `origin` for type `Union`. 

Since the new `UnionType` is compatible with `typing.Union` (according to documentation) it's probably should be easy to fix. I could do this, but I need to understand, what could be affected by this. Is it will be enough to check all usages of Union type and fix it carefully? Also, it's probably should be some kind of a function `is_union` to make it work for versions before 3.10.

**Additional info**

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
pydantic version: 1.8.2
            pydantic compiled: False
                 install path: /Users/drjackild/.pyenv/versions/3.10.0/envs/groups/lib/python3.10/site-packages/pydantic
               python version: 3.10.0 (default, Oct  7 2021, 17:08:09) [Clang 13.0.0 (clang-1300.0.29.3)]
                     platform: macOS-11.6-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

```py
from pydantic import BaseModel

class A(BaseModel):
    s: str | None
```

Raises exception:
```
    
Traceback (most recent call last):
  File "/Users/drjackild/.pyenv/versions/groups/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3444, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-16-a6ee5ea43ee8>", line 1, in <module>
    class A(BaseModel):
  File "/Users/drjackild/.pyenv/versions/groups/lib/python3.10/site-packages/pydantic/main.py", line 299, in __new__
    fields[ann_name] = ModelField.infer(
  File "/Users/drjackild/.pyenv/versions/groups/lib/python3.10/site-packages/pydantic/fields.py", line 411, in infer
    return cls(
  File "/Users/drjackild/.pyenv/versions/groups/lib/python3.10/site-packages/pydantic/fields.py", line 342, in __init__
    self.prepare()
  File "/Users/drjackild/.pyenv/versions/groups/lib/python3.10/site-packages/pydantic/fields.py", line 451, in prepare
    self._type_analysis()
  File "/Users/drjackild/.pyenv/versions/groups/lib/python3.10/site-packages/pydantic/fields.py", line 626, in _type_analysis
    raise TypeError(f'Fields of type "{origin}" are not supported.')
TypeError: Fields of type "<class 'types.UnionType'>" are not supported.
```

**Comment by samuelcolvin** [comment] 2021-10-07 20:49
I'll try to get a new release out asap.

**Comment by DrJackilD** [comment] 2021-10-20 13:18
I'll reopen the issue just to keep it visible until release

**Comment by roganartu** [comment] 2021-11-18 06:47
I think there's a related bug that, based on the existing fix in master, I think would also be fixed by this. I wanted to share the trace here in case it helps someone googling, but didn't think it was worthy of a separate issue. If you disagree let me know and I'll raise one.

Given:
```
from typing import Optional

import pydantic

class Settings(pydantic.BaseSettings):
    works: Optional[str] = None
    broken: str | None = None

Settings()
```
One gets:
```
/tmp/pydantic via 🐍 v3.10.0 (env) on ☁️  (us-east-1) took 2s 
❯ ./poc.py          

/tmp/pydantic via 🐍 v3.10.0 (env) on ☁️  (us-east-1) took 142ms 
❯ works=test ./poc.py

/tmp/pydantic via 🐍 v3.10.0 (env) on ☁️  (us-east-1) took 148ms 
❯ works=test broken=test ./poc.py
Traceback (most recent call last):
  File "/tmp/pydantic/env/lib/python3.10/site-packages/pydantic/env_settings.py", line 172, in __call__
    env_val = settings.__config__.json_loads(env_val)  # type: ignore
  File "/home/tl/.pyenv/versions/3.10.0/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/home/tl/.pyenv/versions/3.10.0/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/tl/.pyenv/versions/3.10.0/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/tmp/pydantic/./poc.py", line 10, in <module>
    Settings()
  File "/tmp/pydantic/env/lib/python3.10/site-packages/pydantic/env_settings.py", line 37, in __init__
    **__pydantic_self__._build_values(
  File "/tmp/pydantic/env/lib/python3.10/site-packages/pydantic/env_settings.py", line 63, in _build_values
    return deep_update(*reversed([source(self) for source in sources]))
  File "/tmp/pydantic/env/lib/python3.10/site-packages/pydantic/env_settings.py", line 63, in <listcomp>
    return deep_update(*reversed([source(self) for source in sources]))
  File "/tmp/pydantic/env/lib/python3.10/site-packages/pydantic/env_settings.py", line 174, in __call__
    raise SettingsError(f'error parsing JSON for "{env_name}"') from e
pydantic.env_settings.SettingsError: error parsing JSON for "broken"

/tmp/pydantic via 🐍 v3.10.0 (env) on ☁️  (us-east-1) took 137ms 
✗❯ works=test broken='"test"' ./poc.py
Traceback (most recent call last):
  File "/tmp/pydantic/./poc.py", line 10, in <module>
    Settings()
  File "/tmp/pydantic/env/lib/python3.10/site-packages/pydantic/env_settings.py", line 36, in __init__
    super().__init__(
  File "/tmp/pydantic/env/lib/python3.10/site-packages/pydantic/main.py", line 406, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for Settings
broken
  instance of UnionType expected (type=type_error.arbitrary_type; expected_arbitrary_type=UnionType)
```
The JSON error confused me when googling this initially after updating a FastAPI project of mine to 3.10 and making no other changes. I believe it happens because the lack of support for `UnionType` breaks the `field.is_complex()` check, causing pydantic to attempt to parse it as JSON.

**Comment by AlexanderPodorov** [comment] 2021-11-18 08:45
+1 on this

**Comment by Toreno96** [comment] 2021-12-04 14:24
+1

**Comment by Bobronium** [comment] 2021-12-04 15:19
### If I may, I'd want to discourage people from posting comments like "+1". 

The issue is already confirmed and acknowledged by maintainer, fix will be available with the next release: https://github.com/samuelcolvin/pydantic/issues/3300#issuecomment-938145241.

These comments are noisy for everyone subscribed to this issue, while providing no value at all.

You can subscribe to this issue if you wish to be notified when it will be fixed.

In the meanwhile you can use this as a workaround: https://github.com/samuelcolvin/pydantic/issues/3300#issuecomment-950122191.

**Comment by Toreno96** [comment] 2021-12-04 17:05
@Bobronium sorry for the noise then.

For me personally, "+1" comments are having the value of noticing the maintainer there are actually people interested in the fix (and I see this practice is very common in open-source projects, so I wasn't aware this can be bad), especially considering the [ #3300 (comment)](https://github.com/samuelcolvin/pydantic/issues/3300#issuecomment-938145241) was actually from a few months ago and there's still no release yet.

But you're arguments are perfectly valid and if you see the alternative solution for that (do you see if and how many people subscribe to the issue?) then I'm happy to oblige 😅

**Comment by Bobronium** [comment] 2021-12-04 18:14
@Toreno96, no worries. Sorry if my comment read too grumpy 🙆🏻.  

Let me elaborate on why I personally think that "+1" comments are _usually_ a bad idea.

Let's start with better alternative first: reactions. 
I think it's a great feature for showing the number of people agree/interested/grateful/upset with a comment/issue.
Unlike comments, it doesn't increase the amount of noise and saves the issue from being flooded: imagine googling this issue and seeing 30+ comments with plain "+1" or "same here". It's not hard to imagine that people won't even attempt to read the rest of the comments, and instead will post yet another "+1" and leave.

While I understand your concern and desire to give a notice to the maintainer, I don't think "+1" would be the best approach for that. I believe maintainers are already very aware of this, and many other issues. I think some form of discussion here would be more applicable if, for example, `pydantic` had a new release that didn't address this issue. But currently, It's not a question "whether this issue will be fixed", or even "when" (fix is already in `master`), but "when will see the new release".

So I'm not discouraging any conversations, I just believe that "+1" is not a great start for one, especially in given situation :)

**Comment by artemijan** [comment] 2021-12-17 08:12
Hi guys, I believe the fix suggested in https://github.com/samuelcolvin/pydantic/issues/3300#issuecomment-950122191 will not be working for the following case:
`
class SericesList(BaseModel):
    services: list[EcsServiceBase|EcsServiceState]
`

**Comment by Halkcyon** [comment] 2022-01-25 00:26
I remember running into this problem when testing 3.10 with Pydantic and found this topic.  It appears like it's no longer a problem with the release of 1.9 (https://github.com/samuelcolvin/pydantic/pull/2885)

It looks like this issue is now resolved.

**Closed** 2022-01-25 01:16 UTC
Labels: bug

**Comment by Toreno96** [comment] 2022-02-02 10:51
Sorry for reopening the issue, and sorry if that's not the best place to ask this question, but IMHO it's pretty related:

Python 3.7 also supports the new UnionType if `from __future__ import annotations` is used:
```python
$ python
Python 3.7.12 (default, Oct 13 2021, 06:51:32)
[Clang 11.0.0 (clang-1100.0.33.17)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> foo: str | None = None
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
>>> from __future__ import annotations
>>> foo: str | None = None
>>> foo is None
True
```

But it does not work in Pydantic 1.9:
`example.py`
```python
from __future__ import annotations

from pydantic import BaseModel


class Foo(BaseModel):
    bar: str | None
```

```python
$ python example.py
Traceback (most recent call last):
  File "a.py", line 6, in <module>
    class Foo(BaseModel):
  File "pydantic/main.py", line 187, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/typing.py", line 356, in pydantic.typing.resolve_annotations
    if self._name == 'Optional':
  File "/usr/local/Cellar/python@3.7/3.7.12_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/typing.py", line 263, in _eval_type
    return t._evaluate(globalns, localns)
  File "/usr/local/Cellar/python@3.7/3.7.12_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/typing.py", line 467, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```

Is it something that could be supported in the future, or such backward compatibility is out of scope?

**Comment by ikamensh** [comment] 2022-02-09 17:14
same as above happens for python 3.8

**Comment by PrettyWood** [comment] 2022-02-09 17:21
Hi everyone
You need to understand that `int | str` **is not valid at runtime** for python < 3.10 as type doesn't implement `__or__`.
It is valid at **interpretation time** by adding `from __future__ import annotations` but pydantic can't do magic and change how python works at runtime.
It opened a while ago https://github.com/samuelcolvin/pydantic/pull/2609, which works for python < 3.10 by using https://github.com/PrettyWood/future-typing, which changes at interpretation time `int | str` into `Union[int, str]` for example
Hope it clarifies things

**Comment by Toreno96** [comment] 2022-02-10 07:47
@PrettyWood thank you very much for the answer and detailed explanation 🙏

**Comment by GregHilston** [comment] 2022-09-03 14:15
I'm actually experiencing this on Python `3.10.4` with Pydantic `1.10.1`.

```
class PromptData(BaseModel):
    image = PIL.Image.Image | None
```
results in:

```
    class PromptData(BaseModel):
  File "pydantic/main.py", line 222, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 506, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 557, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 831, in pydantic.fields.ModelField.populate_validators
  File "pydantic/validators.py", line 752, in find_validators
RuntimeError: no validator found for <class 'types.UnionType'>, see `arbitrary_types_allowed` in Config
```

**Comment by Bobronium** [comment] 2022-09-03 14:24
@GregHilston, seems like a different issue to me.

First of all, does this work as expected?
```py
class PromptData(BaseModel):
    image = PIL.Image.Image

    class Config:
        arbitrary_types_allowed = True 
```

**Comment by GregHilston** [comment] 2022-09-03 15:12
@Bobronium My apologies on the weak minimum code example. Thanks for doing this leg work to better understand what I was saying :)

**Comment by hramezani** [comment] 2022-09-03 15:31
shouldn't we replace `=` with `:` when we define variables in model?
`a = Optional[str]`  -> `a: Optional[str]`

**Comment by Bobronium** [comment] 2022-09-03 15:36
Ah, of course... Thank you so much! I thought I started to go crazy.

**Comment by GregHilston** [comment] 2022-09-05 15:02
@hramezani Oh my god. That's hilarious that I totally didn't see that... I'm embarrassed ha

**Comment by Spenhouet** [comment] 2024-05-15 15:17
From the issue history I can not figure out as of which version the Python 3.10 union type is supported. Comments above suggested 1.9 and 1.10.2, but we are already on 1.10.2 and are getting

> AttributeError: 'types.UnionType' object has no attribute '__name__'

for 

```python
computed: str | None = ComputedField()
```

We just adopted Ruff, and one rule is autofixing

```python
computed: Optional[str] = ComputedField()
```

to the new python 3.10 union type, which is what we want, but it makes our pydantic model related unit tests fail.

What is the minimal pydantic version which we need to update to?

**Comment by Halkcyon** [comment] 2024-05-25 15:06
A lot has changed in almost 3 years and a major version / rewrite of Pydantic has happened in the meantime @Spenhouet It might be worth just updating to latest, fixing your breaks, and see if the intermediate versions resolve your problem.
