### ISSUE TITLE
BaseSettings can't parse a simple json from env

### ISSUE THREAD

**Issue by victornoel** [samuelcolvin/pydantic#831] opened 2019-09-23 16:50 UTC
# Bug

Please complete:
* OS: **Linux**
* Python version `import sys; print(sys.version)`: **3.7.4**
* Pydantic version `import pydantic; print(pydantic.VERSION)`: **0.32.2**

I have this:
```py
from typing import Optional, Set
from pydantic import BaseSettings, BaseModel


class SubSettings(BaseModel):
    a: str
    b: Set[str] = set()

    class Config:
        allow_mutation = False


class Settings(BaseSettings):
    sub: Optional[SubSettings] = None

    class Config:
        env_prefix = 'MY_'
        allow_mutation = False


SETTINGS = Settings()
```

Running:
```
MY_SUB='{"a": "aaaa", "b": ["bbbb"]}' pipenv run python test.py

Traceback (most recent call last):
  File "test.py", line 21, in <module>
    SETTINGS = Settings()
  File "pydantic/env_settings.py", line 25, in pydantic.env_settings.BaseSettings.__init__
  File "pydantic/main.py", line 275, in pydantic.main.BaseModel.__init__
  File "pydantic/main.py", line 785, in pydantic.main.validate_model
pydantic.error_wrappers.ValidationError: 2 validation errors for Settings
sub
  value is not a valid dict (type=type_error.dict)
sub
  value is not none (type=type_error.none.allowed)

```

I'm expecting this to work but it doesn't, am I missing something or is there a bug?

**Comment by victornoel** [comment] 2019-09-23 16:51
For the record I have also tested with `sub: SubSettings = SubSettings()` but I then get:
```
Traceback (most recent call last):
  File "test.py", line 13, in <module>
    class Settings(BaseSettings):
  File "test.py", line 14, in Settings
    sub: SubSettings = SubSettings()
  File "pydantic/main.py", line 275, in pydantic.main.BaseModel.__init__
  File "pydantic/main.py", line 785, in pydantic.main.validate_model
pydantic.error_wrappers.ValidationError: 1 validation error for SubSettings
a
  field required (type=value_error.missing)
```

**Comment by dmontagu** [comment] 2019-09-23 18:27
A couple quick points:
1. shouldn't it be `MY_SUB='{"a": "aaaa", "b": ["bbbb"]}'`? Is there a reason you didn't include curly braces?
2. You might need to add a `pre=True` validator to `Settings` (on the `sub` field) that will parse a string into a dict

**Comment by victornoel** [comment] 2019-09-24 06:56
@dmontagu ah yes, sorry, it's a typo, my real use case does use the curly braces and I validate that my sample above does have the problem (I updated the description) :)

It does work if I use my own validator (which is actually a parser…):
```py
class SubSettings(BaseModel):
    a: str
    b: Set[str] = set()

    class Config:
        allow_mutation = False


class Settings(BaseSettings):
    sub: Optional[SubSettings] = None


    @validator('sub', pre=True)
    def json_decode(cls, v):
        if isinstance(v, str):
            try:
                return json.loads(v)
            except ValueError:
                pass
        return v

    class Config:
        env_prefix = 'MY_'
        allow_mutation = False
```

I don't get why I do need to implement my own parser for the subfield when the documentation clearly says this should be supported (see https://pydantic-docs.helpmanual.io/#id5 with the `MY_PREFIX_MORE_SETTINGS` example).
Is this a bug or a limitation?

**Comment by dmontagu** [comment] 2019-09-24 07:27
It looks like the problem is that the `Union` causes the field to pass the `field.is_complex()` test to determine whether it should load the value.

If you annotate the field as non-optional (even if you leave the default as None), it works:
```python
class Settings(BaseSettings):
    sub: SubSettings = None

    class Config:
        env_prefix = 'MY_'
        allow_mutation = False
```

@samuelcolvin what do you think the right behavior should be here?

**Comment by victornoel** [comment] 2019-09-24 07:32
@dmontagu indeed, good point, it works without the optional :) glad we found the origin of the problem!

**Comment by dmontagu** [comment] 2019-10-07 06:49
For what it's worth, I ran the script at the top of the issue, and it appears to be fixed in v1.

I'll leave the issue open for now, but I think it can be closed once v1 is released (assuming it still works then).

**Comment by victornoel** [comment] 2019-10-07 06:52
@dmontagu great, I suppose it is also solved by the beta you just released? I will try it and close this issue if it's working

**Comment by dmontagu** [comment] 2019-10-07 08:23
I believe so. I just tested against the master branch, but I don’t think anything has been committed since the beta release that would change this behavior.

**Closed** 2019-10-17 14:28 UTC
Labels: bug
