### ISSUE TITLE
Auto-completion when instantiating BaseModel objects

### ISSUE THREAD

**Issue by marlonjan** [samuelcolvin/pydantic#650] opened 2019-07-10 08:34 UTC
# Feature Request

Hi! Currently auto-completion does not work well when calling the initializer of classes that inherit from pydantic.BaseModel, at least in IntelliJ / PyCharm.

Are there any plans to improve that? Auto-completion works nicely with dataclasses from the python 3.7 standard library. Same applies to highlighting type mismatches or missing arguments in the call. Here is a comparison of the behavior in IntelliJ:

![image](https://user-images.githubusercontent.com/9771046/60953436-72535400-a2fd-11e9-918d-a0c7af2b2f2d.png)

![image](https://user-images.githubusercontent.com/9771046/60953265-243e5080-a2fd-11e9-9a70-693881fad902.png)

Code example to reproduce the screenshots:
```py
from pydantic import BaseModel
from dataclasses import dataclass


class User(BaseModel):
    id: int
    name: str
    age: float


@dataclass
class UserDataclass:
    id: int
    name: str
    age: float


# no auto-completion
user = User()

# auto-completion
user_dataclass = UserDataclass()
```

Thanks for creating pydantic! Best regards,
Marlon

**Comment by timonbimon** [comment] 2019-07-10 08:51
adding auto-completion support would be huge!

**Comment by dmontagu** [comment] 2019-07-10 09:46
I would also love to see this.

`attrs` seems to be able to (very flexibly) generate a mypy-compatible type-hinted `__init__`, so I think this might be possible, at least in theory.

However, one potential issue is that parsing is performed during initialization, so you may purposely want to avoid using annotated types as type hints on the initialization kwargs. I do think it would be nice to have a type-hinted `__init__` (or other method, I suppose) for creating model instances where parsing is known to be unnecessary, even if it means that a separate method had to be used for type-hint-safe parsing (I expect this could have some performance benefits as well).

If I recall correctly, there has been some discussion of replacing the use of `BaseModel.__init__` with `BaseModel.parse_object` (or something similar) for parsing; I would expect that would be necessary for compatibility with a type-hinted `__init__`. @samuelcolvin I would be interested to get your take on whether that is realistic.

**Comment by samuelcolvin** [comment] 2019-07-10 10:27
I would love this too.

I don't know how pycharm builds suggestions, does it use mypy or it's own parsing?

A mypy plugin as suggested in #460 would fix this case in mypy, but would it help in pycharm?

Maybe @pauleveritt who I think uses pydantic and works for pycharm might know?

I'm at pycharm europe now which is sponsored by pycharm so maybe I can find a real human being to ask.

**Comment by dmontagu** [comment] 2019-07-10 11:17
Okay, I dug into this just a little:

1. it looks like mypy ships with an attrs-specific plugin to make the __init__ checking work: https://github.com/python/mypy/blob/master/mypy/plugins/attrs.py
1. I don't have a reference on me, but I've looked into this in the past, and if I recall correctly, PyCharm has a custom extension to ensure attrs `__init__`s look right. (Presumably this is also how they are handling dataclass). So it might be hard to get this support in a native way (though it would be great to hear from JetBrains if they had any suggestions).

Separately, I think it might be possible to achieve this by "tricking" the IDE in a variety of ways. I played with various approaches involving `TYPE_CHECKING`, but I think the one I currently like best is the following:
![Screen Shot 2019-07-10 at 4 16 34 AM](https://user-images.githubusercontent.com/35119617/60964924-6c438000-a2c9-11e9-9274-ecbe7682a8a3.png)


This behaves as though undecorated at runtime, but seems to behave properly with both PyCharm and mypy (retaining all desired autocomplete behavior for the BaseModel class).

@samuelcolvin I don't know how great this trick is as a long term solution, but for the sake of "paving the way" for such a capability it would probably makes sense to push in the direction of changing the use of the `__init__` method so it is never expected to be called with incorrect types (i.e., for parsing). Maybe this could be a 1.0 thing?

**Comment by samuelcolvin** [comment] 2019-07-10 11:21
Just spoken to pycharm in person, short answer is that we would need to build a pycharm extension in Java or kotlin to do this, attrs or dataclass code is open source and would be a good starting point.

**Comment by koxudaxi** [comment] 2019-07-10 15:41
I want to support auto-completion on PyCharm.
@samuelcolvin 
Thank you for asking the person.

I have searched issues and source code for attrs and dataclass.
The issue is to support auto-completion for attrs.
https://youtrack.jetbrains.com/issue/PY-26354

Also, we can find related commit(source code) by the issue number(PY-26354) in intellij-community repository.
https://github.com/JetBrains/intellij-community/search?o=asc&p=1&q=PY-26354&s=author-date&type=Commits

JetBrains developer implemented auto-completion for attrs and dataclass by request.
However, I don't know we should request to the developers.

if you already know the information, then I'm sorry.

**Comment by gmetzker** [comment] 2019-07-10 17:56
This would be a great feature / plugin!

**Comment by samuelcolvin** [comment] 2019-07-10 18:13
Jet brains people were very nice but said pydantic is not popular enough for them to build the plugin themselves, however they will help if we have any issues.

**Comment by pauleveritt** [comment] 2019-07-11 15:31
Yes, I'm watching on this ticket. I'm here at EuroPython with the PyCharm team. If anybody has any questions about compiling PyCharm from GitHub, making a plugin, or what the specifics about a pydantic plugin, let me know.

**Comment by koxudaxi** [comment] 2019-07-12 06:19
@pauleveritt 
Thank you for watching the issue.
I have a question, Should we make a plugin or patching Pycharm?  
If we can merge the feature on PyCharm then, I think that it is the best way.
However, I don't know you and your company want to merge the feature on the mainstream.


Btw, I have patched PyCharm and build it for auto-completion.
![2019-07-12 14 58 44](https://user-images.githubusercontent.com/630670/61105866-2ac3f800-a4b6-11e9-8244-348750665c1e.png)

It's an experimental challenge yet. Console show errors :(

**Comment by dmontagu** [comment] 2019-07-12 10:59
@koxudaxi Would you be willing to share your implementation?

**Comment by pauleveritt** [comment] 2019-07-12 11:33
@koxudaxi sorry for the delay in replying, I'm working the PyCharm booth at EuroPython. Kudos for getting as far as you have! I can probably get someone from the PyCharm team to look at your code if you can put it in a gist or in a fork.

As you might imagine, PyCharm tries to be careful about the things it commits to supporting. Over the years it adds up, and we have to keep supporting things even when most people stop using them. So it's better to do it as a plugin and, if it becomes popular, we could discuss a merge.

**Comment by koxudaxi** [comment] 2019-07-12 12:32
> @koxudaxi Would you be willing to share your implementation?

@dmontagu sorry, I have forgotten it. 
This commit is a prototype. if we hope to publish it then we need to implement more code.
I could add ``pydantic.dataclass`` easy. but,  we will need to spend time to implement ``BaseModel`` which is different from other dataclasses like attrs.  

https://github.com/koxudaxi/intellij-community/commit/c654365f925cd9288518514d09632454830f356d

**Comment by koxudaxi** [comment] 2019-07-12 12:56
@pauleveritt
Thank you for your explanation.  It's all clear now.
I try to create a plugin :)

Also, I use Jetbrains products every day, which increase development speed. If I contribute to your community, I'm happy. Thank you.

**Comment by marlonjan** [comment] 2019-07-12 13:36
Thanks to all of you for taking a look at this!!

**Comment by pauleveritt** [comment] 2019-07-12 15:45
Thank you @koxudaxi and if you want me to get someone from the team to review, let me know.

I personally am very, very happy...VERY happy...to see you work on this.

**Comment by koxudaxi** [comment] 2019-07-12 16:00
@pauleveritt
Thank you for your kindness. If we need some help, then we ask it to you.

**Comment by dmontagu** [comment] 2019-08-06 23:54
@koxudaxi any chance you could explain how to build pycharm to make use of your modification? (Or point me in the direction of a guide?) I've never worked with custom pycharm plugins.

Related, I've made some progress on a mypy plugin, linked on this issue: https://github.com/samuelcolvin/pydantic/issues/460. It is definitely doesn't behave properly under all circumstances, but it at least works for me to type-check `BaseModel.__init__` for all of the models I use (which probably follow some conventions that keep it away from the as-yet unhandled edge cases).

**Comment by koxudaxi** [comment] 2019-08-07 04:41
@dmontagu
>  Do you know if it is hard to use the plugin with the pro version of PyCharm? (It looks like building is against the community version; not sure what it looks like to integrate with pro.)

I use the plugin in the pro version.
However, the plugin is on a very experimental phase.
It happens a lot of errors. @MrMrRobat have reported (https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/1)

> It looks like building is against the community version; not sure what it looks like to integrate with pro.

Sorry, I don't know it. I must learn how to build a plugin for each edition.
I will try to fix the plugin this week.

I have checked your mypy-plugin, I feel a great start. :)
If we cant use mypy-plugin to do auto-complete and check types in Pycharm, then I think the best way.
We can maintain the plugin easier than Kotlin-plugin.

**Comment by dmontagu** [comment] 2019-08-07 06:35
Yeah, I was pleasantly surprised how easy it was to work with once I got started.

Related, there also appears to be some good infrastructure for calling mypy runs from within python, which I think would enable us to more easily/incrementally add mypy tests (in particular, expected fails) than the current system.

I would be surprised if the mypy plugin worked directly with PyCharm, so it would probably still be nice to build an autocomplete plugin for PyCharm.

@koxudaxi if you can think of any specific requests for the mypy plugin beyond type checking the `__init__` call, please post them to #460 and I'll try to add them.

**Comment by koxudaxi** [comment] 2019-08-07 18:00
@dmontagu 
I have fixed easy bugs on my pycharm-plugin. I continue developing the plugin.
OK, I will post some request or question on the issue. 
Thank you.

**Comment by samuelcolvin** [comment] 2019-08-10 17:27
great work @koxudaxi.

Feel free to ping me here if there's anything I can do to help make plugin development easier in pydantic.

**Comment by koxudaxi** [comment] 2019-08-15 13:50
The PyCharm plugin for Pydantic is now available on JetBrains Plugins Repository. 
The Plugin can be installed from Marketplace (PyCharm's Preferences -> Plugin -> Marketplace) 

The Plugin page is https://plugins.jetbrains.com/plugin/12861-pydantic

Also, I am developing the plugin on this repository https://github.com/koxudaxi/pydantic-pycharm-plugin
If you have any opinion, Would you please leave feedback?
I'm waiting for your bug reports and feature requests, PRs.

**Comment by samuelcolvin** [comment] 2019-08-15 14:23
Fantastic, well done.

I've installed it and at first glance it seems to do everything I need.

**Comment by samuelcolvin** [comment] 2019-08-15 14:24
@koxudaxi would you consider submitting a PR to adding this to the documentation?

**Comment by koxudaxi** [comment] 2019-08-15 14:40
@samuelcolvin 
I am happy seeing your good response 😄 

OK, I will create the PR.

**Comment by davideasaf** [comment] 2020-04-17 17:15
Hey everyone, 

Does anyone know if a similar solution exists within VsCode? Auto-completion when instantiating BaseModel objects would be awesome there as well.

**Comment by RafalSkolasinski** [comment] 2020-07-19 13:09
I just hit the completion problem when using Sublime with LSP and python-language-server.

Took me a while to figure out that completion for methods in class inheriting from `BaseModel` are not working and it's not something wrong with my code ;)

Any good workarounds until this is resolved?

**Comment by talarari** [comment] 2020-10-15 21:59
i'm using vscode and would really like to have auto completion for creating models.
static type checkers (pyright for example) have no way of knowing what the arguments for __init__ are, but they do work well with dataclasses

would it make sense to have a class inherit from BaseModel **and** be decorated with @dataclass ?
```python
from dataclasses import dataclass
from pydantic import BaseModel

@dataclass
class User(BaseModel):
    id: int
    name: str
    age: float

```

**Comment by MrMrRobat** [comment] 2020-10-15 22:09
> would it make sense to have a class inherit from BaseModel **and** be decorated with dataclass ?

I doubt that code above would work properly, but what you can try is to make fake `dataclass` decorator and trick type checker to believe that it's decorated with real `dataclass`:

```py
from pydantic import BaseModel

if TYPE_CHECKING:
    from dataclasses import dataclass
else:
    def dataclass(model):
        return model

@dataclass
class User(BaseModel):
    id: int
    name: str
    age: float
```

**Comment by talarari** [comment] 2020-10-16 08:23
That might work , the thing is I don't want to trick my team mates when I trick the type checker ..

**Comment by talarari** [comment] 2020-10-16 09:48
using @MrMrRobat advice i currently went with this workaround which seems to work with vscode and is not terribly misleading:

created an auto_complete_only.py helper and aliased @ dataclass to @ autocomplete
```python
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from dataclasses import dataclass
else:

    def dataclass(model):
        return model


autocomplete = dataclass

```

![image](https://user-images.githubusercontent.com/4973087/96243081-ea9ecf80-0fac-11eb-9ccc-ba703c104293.png)

**Comment by StephenBrown2** [comment] 2020-11-11 20:33
Could even be simpler (tho untested):
```python
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from dataclasses import dataclass as autocomplete
else:
    def autocomplete(model):
        return model
```
🤷‍♂️

**Comment by JosXa** [comment] 2020-12-12 02:00
> using @MrMrRobat advice i currently went with this workaround which seems to work with vscode and is not terribly misleading:
> 
> created an auto_complete_only.py helper and aliased @ dataclass to @ autocomplete
> 
> ```python
> from typing import TYPE_CHECKING
> 
> if TYPE_CHECKING:
>     from dataclasses import dataclass
> else:
> 
>     def dataclass(model):
>         return model
> 
> 
> autocomplete = dataclass
> ```
> 
> ![image](https://user-images.githubusercontent.com/4973087/96243081-ea9ecf80-0fac-11eb-9ccc-ba703c104293.png)

![image](https://user-images.githubusercontent.com/7313176/101969695-28734980-3c26-11eb-8337-40180462427d.png)

Oh god, you must be kidding me. Pyright is so incredibly buggy...

**Comment by MrMrRobat** [comment] 2020-12-12 09:24
@JosX, as I understand, it's more a cosmetic issue, but you can try this workaround to use workaround above 🙃 without warnings:

```
from typing import TYPE_CHECKING

# trick PyRight into thinking that it might be both False or True
RUNTIME = not TYPE_CHECKING

if RUNTIME:
    def autocomplete(model):
        return model
else:
    from dataclasses import dataclass as autocomplete
```

I didn't test it, but it _should_ work.

**Comment by samuelcolvin** [comment] 2020-12-18 14:50
I'm closing this as pycharm has an excellent plugin built by @koxudaxi and vscode support is discussed in https://github.com/microsoft/python-language-server/issues/1898

It sounds like any further solution either requires changes to the language servers or third party plugins.

If there are any tweaks pydantic can make to make the jobs of language servers easier, please create a new issue.

If anyone succeeds in building a useful plugin, please create a PR to update the docs.

**Closed by samuelcolvin** 2020-12-18 14:50 UTC
Labels: Feedback Wanted, feature request

**Comment by adamal** [comment] 2021-01-07 16:21
Very nice to find that a workaround exists even if somewhat hacky.

I came up with this simple extension of the idea – here adapted for `BaseModel`. 

With this, you can import `BaseModel` from here (say `type_help.py`) in stead of from `pydantic`, and if/when a proper solution becomes available, you can just switch your import references without removing a host of `@autocomplete`-annotations.

```python3
from typing import TYPE_CHECKING
from pydantic import BaseModel as _BaseModel

# trick PyRight into thinking that it might be both False or True
RUNTIME = not TYPE_CHECKING

if RUNTIME:
    def base_model(model):
        return model
else:
    from dataclasses import dataclass as base_model

@base_model
class BaseModel(_BaseModel): ...
```

**Comment by podj** [comment] 2021-05-27 13:18
@koxudaxi Hey man, great job!
Let me know if you need any help in the maintenance! You've saved lives my friend!

**Comment by amir20** [comment] 2021-12-27 23:48
For anybody following this issue, the fix has been [merged](https://github.com/samuelcolvin/pydantic/pull/2721) and available in version `1.9.0a2`.

**Comment by Tomperez98** [comment] 2021-12-29 23:08
When will `v 1.9.0` be available?

**Comment by samuelcolvin** [comment] 2021-12-29 23:27
Next few days.

**Comment by masreplay** [comment] 2022-01-05 22:11
@samuelcolvin now I'm using  [SQLModel](https://github.com/tiangolo/sqlmodel) and autocompletion it's not with Pycharm work
