### ISSUE TITLE
int not recognized as PositiveInt

### ISSUE THREAD

**Issue by timonbimon** [samuelcolvin/pydantic#776] opened 2019-08-21 11:17 UTC
# Bug

Please complete:
* OS: **Mojave OS**
* Python version `import sys; print(sys.version)`: **3.7.3**
* Pydantic version `import pydantic; print(pydantic.VERSION)`: **0.32.2**

Just a minor, minor issue with PyCharm. Really nothing too important, but I thought I'd still mention it. Have a look:

![image](https://user-images.githubusercontent.com/14793026/63427548-a8641780-c415-11e9-9c92-2e285456afe7.png)

It complains that int is not a PositiveInt, but that seems like an unnecessary warning.

**Comment by timonbimon** [comment] 2019-08-21 11:18
Ooh feel free to remove the bug label (not sure how to to that), that seems a little excessive

**Comment by samuelcolvin** [comment] 2019-08-21 11:20
wrong package and duplicate of https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/36

**Closed by samuelcolvin** 2019-08-21 11:20 UTC
Labels: bug
