### ISSUE TITLE
`pydantic_encoder` not working with primitive types

### ISSUE THREAD

**Issue by startakovsky** [samuelcolvin/pydantic#699] opened 2019-07-30 22:18 UTC
What is the recommended way to use `pydantic_encoder`?

I would like to use it on the values of a dict returned by `model.dict()` to make them json-serializable?

Here is a class I use as a mixin with BaseModel: 

```python
class BaseModelPortalExtra:
    def dict_jsonable(self):
        return {k: pydantic_encoder(v) for k, v in self.dict().items()}
```

And it works great! Except when I have a value that is of a primitive type such as a `str`. Is it best practice here to create my own dict and do something akin to? https://gist.github.com/samuelcolvin/1647958c99cc59873f36400048d77ae2

https://github.com/samuelcolvin/pydantic/blob/b58f31dfd9d99e8268eb4eca62c7a404d5dc58c6/pydantic/json.py#L44

**Comment by samuelcolvin** [comment] 2019-07-31 08:42
Sort of a duplicate of #317, see the discussion there.

`pydantic_encoder` is for use with the `default` argument of `json.dumps`

**Comment by startakovsky** [comment] 2019-08-08 05:04
@samuelcolvin I found this from fastapi and it does the trick! probably worth an update in the documentation and those related dict/json pydantic_encoder issues.

docs: https://fastapi.tiangolo.com/tutorial/encoder/
code: https://github.com/tiangolo/fastapi/blob/033bc2a6c9aec3a245eb1f1b4fadb2fbb7a514b8/fastapi/encoders.py#L9

**Comment by samuelcolvin** [comment] 2019-08-08 08:40
Unless I'm missing something, neither the fastapi or pydantic docs say that `pydantic_encoder` is designed for direct use.

What documentation would you suggest?

**Comment by startakovsky** [comment] 2019-08-08 15:47
pydantic_encoder aside, I’m just saying that it was not clear to me that if I want a json-dumpable dictionary values that I don’t have to roll my own implementation. 

In conclusion, now it is clear I can do a model.json() for json, model.dict() for an ordinary dictionary that preserves complex types, and fastapi.encoders.jsonable_encoder(model) to get a json-dumpable dictionary.

**Closed** 2019-10-17 14:38 UTC
Labels: question
