### ISSUE TITLE
Ignore private, leading _ variables when validate_assignment=True

### ISSUE THREAD

**Issue by MaxNoe** [samuelcolvin/pydantic#1151] opened 2020-01-06 16:37 UTC
# Feature Request

We'd like to configure public (no leading `_`) variables using pydantic with `validate_assignment` but still would like private variables `_` to be possible, e.g. for logging:

```python
import pydantic
import logging


class ModelWithLog(pydantic.BaseModel):
    option: int = 10

    class Config:
        validate_assignment = True

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self._log = logging.getLogger(self.__class__.__name__)  # This fails


m = ModelWithLog()
m.option = 'foo'  # this should fail
m.optoin = 10     # typo, this should fail as well
```

Result:
```
Traceback (most recent call last):
  File "model_log.py", line 15, in <module>
    m = ModelWithLog()
  File "model_log.py", line 12, in __init__
    self._log = logging.getLogger(self.__class__.__name__)  # This fails
  File "pydantic/main.py", line 281, in pydantic.main.BaseModel.__setattr__
ValueError: "ModelWithLog" object has no field "_log"```

**Comment by samuelcolvin** [comment] 2020-01-06 16:42
duplicate of #655, please comment there.

**Closed by samuelcolvin** 2020-01-06 16:42 UTC
Labels: feature request

**Comment by MaxNoe** [comment] 2020-01-06 16:50
Ah, sorry did not find this issue somehow.
