### ISSUE TITLE
Self referencing models: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by lyz-code** [samuelcolvin/pydantic#2279] opened 2021-01-21 14:00 UTC
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.7.3
            pydantic compiled: True
                 install path: ~/.venvs/repository-pattern/lib/python3.7/site-packages/pydantic
               python version: 3.7.3 (default, Jul 25 2020, 13:03:44)  [GCC 8.3.0]
                     platform: Linux-4.19.0-5-amd64-x86_64-with-debian-10.6
     optional deps. installed: ['typing-extensions']
```

An `RecursionError: maximum recursion depth exceeded while calling a Python object` error was raised when accessing self referencing attribute from related models.

Given the following model definition:

```py
from typing import Optional

from pydantic import BaseModel


class A(BaseModel):
    b: Optional["B"] = None


class B(BaseModel):
    a: Optional[A] = None


A.update_forward_refs()

a = A()
b = B()
a.b = b
b.a = a

aa = A()
ba = B()
aa.b = ba
ba.a = aa
```

When running the following code:

```
>> type(a.b.a)
<class '__main__.A'>
>> a.b.a
>> type(aa.b.a)
<class '__main__.A'>
>> aa.b.a
*** RecursionError: maximum recursion depth exceeded while calling a Python object
```

You see that the Recursion error is raised. 

I know this error is related with #1370, but as it's not a self referencing model I thought it was better to open another issue. I don't mind merging it with the other if you feel like it.

It can also be related to #659, #524 and #1345.

I guess until the related issues are not solved, this one is not going to be either, but can anyone help me understand why `a.b.a` works and `aa.b.a` doesn't? It's driving me crazy xD

**Comment by lackofepiphany** [comment] 2021-07-21 13:42
Have you checked to see if there is any name mangling or reserved variables?

**Comment by iliis** [comment] 2022-02-15 10:27
I came across something similiar, although I'm not sure if I should open a new issue for this:

```python
from pydantic import BaseModel

class Foo(BaseModel):
    other: 'Foo' = None

f = Foo()
f.other = f

print(f == f) # crashes
```

The stack trace:
```
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    print(f == f) # crashes
File "pydantic/main.py", line 874, in pydantic.main.BaseModel.__eq__
  File "pydantic/main.py", line 435, in pydantic.main.BaseModel.dict
  File "pydantic/main.py", line 833, in _iter
  File "pydantic/main.py", line 708, in pydantic.main.BaseModel._get_value
  File "pydantic/main.py", line 435, in pydantic.main.BaseModel.dict
  File "pydantic/main.py", line 833, in _iter
  File "pydantic/main.py", line 708, in pydantic.main.BaseModel._get_value
  File "pydantic/main.py", line 435, in pydantic.main.BaseModel.dict
  File "pydantic/main.py", line 833, in _iter
  File "pydantic/main.py", line 708, in pydantic.main.BaseModel._get_value
  [...]
    File "/usr/lib/python3.8/abc.py", line 98, in __instancecheck__
    return _abc_instancecheck(cls, instance)
RecursionError: maximum recursion depth exceeded in comparison
```

Pydantic version:
```
             pydantic version: 1.9.0
            pydantic compiled: True
                 install path: /home/samuel/projects/foo/venv/lib/python3.8/site-packages/pydantic
               python version: 3.8.10 (default, Nov 26 2021, 20:14:08)  [GCC 9.3.0]
                     platform: Linux-5.13.0-28-generic-x86_64-with-glibc2.29
     optional deps. installed: ['typing-extensions']
```

**Comment by iliis** [comment] 2022-02-15 10:30
> I guess until the related issues are not solved, this one is not going to be either, but can anyone help me understand why a.b.a works and aa.b.a doesn't? It's driving me crazy xD

With 1.9.0 it seems both fail.

**Comment by samuelcolvin** [comment] 2022-04-02 14:38
pydantic doesn't (yet) support recursive models.

As far as I know this is a duplicate of #659.

**Closed** 2022-04-02 14:39 UTC
Labels: bug

**Comment by lyz-code** [comment] 2022-04-04 09:00
I'm not sure it's a duplicate, because I'd like to use it without using SQLAlchemy

**Comment by samuelcolvin** [comment] 2022-04-04 09:06
It's all the same route cause - we currently have no cycle breaking feature. It's possible but far from trivial to implement and not a priority right now.

**Comment by samuelcolvin** [comment] 2022-06-29 15:31
This is fixed in pydantic-core, recursion cycles will be safely caught in pydantic v2.

See https://github.com/samuelcolvin/pydantic-core/pull/134.

**Comment by jordan-bucholtz** [comment] 2022-10-11 16:30
@samuelcolvin I noticed this mentioned about the v2 release: "Plan is to have all this done by the end of October, definitely by the end of the year.”. Do you have any further insight as to how far away v2 is? I'd love to use Pydantic, but this issue is a deal-breaker so v2 is a requirement for my use-case.

**Comment by samuelcolvin** [comment] 2022-10-11 16:32
Still aiming for the end of the year. Pretty certain I'll have an alpha release by then, less certain I'll have V2 itself out.

**Comment by quantology** [comment] 2024-01-03 23:31
I've found a case which I think breaks the fix in [PR134](https://github.com/pydantic/pydantic-core/pull/134) (discovered on pydantic 2.3.0):
```python
from typing import TypeAlias
from pydantic import BaseModel

# adapted from https://stackoverflow.com/a/76646986
JSONable: TypeAlias = dict[str, "JSONable"] | list["JSONable"] | str | int | float | bool | None

class ArbitraryData(BaseModel):
    data: JSONable
```

raises: `RecursionError: maximum recursion depth exceeded in __instancecheck__`

**Comment by glesperance** [comment] 2024-04-01 20:40
Got the same problem as @quantology -- we should probably reopen this

**Comment by JayGhiya** [comment] 2024-05-14 06:05
i had a similar issue but was using pydantic version inside of dspy project (that also uses v2 but old one).  i removed dspy functionality upgraded to latest 2.7.* then it fixed.

**Comment by alliefitter** [comment] 2024-06-17 15:35
I've run into this problem while trying to type JSON data like @quantology. I haven't really found a workaround, but I did find out that pydantic includes a `JsonValue` which is basically a fancier version of the `JSONable` type definition above. I don't get the recursion error when using `JsonValue`.

**Comment by elikoga** [comment] 2024-08-21 16:18
Should be reopened

**Comment by dmarteau** [comment] 2024-10-17 14:56
Can someone confirm if a fix for recursive type definition is planned or not ?

While working for recursive BaseModel definition, as of version 2.9.3, any attempt to get json_schema from  recursive type definition  like   `Foo = Union[int,'Foo']`  crash with recursion limit error.
