### ISSUE TITLE
Validation Error response incorrect when using Union and typing_extensions Literals.

### ISSUE THREAD

**Issue by sammaphey** [samuelcolvin/pydantic#1195] opened 2020-01-28 19:46 UTC
# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
pydantic version: 1.3
pydantic compiled: False
install path: /Users/maphey1/Documents/venvs/darc/lib/python3.7/site-packages/pydantic
python version: 3.7.4 (default, Jan 10 2020, 11:11:56)  [Clang 10.0.1 (clang-1001.0.46.4)]
platform: Darwin-18.7.0-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

I am using Fast API on top of pydantic so all of the error validation responses will be in JSON as if they are being returned from Fast API

```py
class SchemaObjectType(SchemaBaseType):
    """Definition for schema object types."""

    type: Literal["object"]
    widget: Literal["dictionary"]
    default: Dict[str, Any] = {}
    properties: Dict[str, Union[
        SchemaReferenceType,
        SchemaListType,
        SchemaOneOfType,
        'SchemaObjectType',
        SchemaDateType,
        SchemaBooleanType,
        SchemaNumberType,
        SchemaTextType
    ]]
    required: List[str]
    order: List[str]


SchemaObjectType.update_forward_refs()


class SchemaData(BaseModel):
    """Definition for schema data."""

    properties: Dict[str, Union[
        SchemaReferenceType,
        SchemaListType,
        SchemaOneOfType,
        SchemaObjectType,
        SchemaDateType,
        SchemaBooleanType,
        SchemaNumberType,
        SchemaTextType
    ]]
    required: List[str]
    order: List[str]
```
Example correct schema: 
```json
{
  "properties": {
    "thing": {
      "description": "desc",
      "type": "object",
      "default": "",
      "widget": "dictionary",
      "properties": {
         "blue": {
           "description": "desc",
           "type": "string",
           "default": "",
           "widget": "default"
         }
      },
      "required": [],
      "order": []
    }
  },
  "required": [],
  "order": []
}
```
When I define a SchemaData JSON object (as above) correctly then I receive no errors. However if I have any error at all (for example I change properties->thing->widget to "dictionar" (which is not the valid Literal) then this is returned as a response: 
```json
{
  "detail": [
    {
      "loc": [
        "body",
        "schemas"
      ],
      "msg": "value is not a valid sequence",
      "type": "type_error.sequence"
    },
    {
      "loc": [
        "body",
        "schemas",
        "properties",
        "thingy",
        "type"
      ],
      "msg": "unexpected value; permitted: 'string'",
      "type": "value_error.const",
      "ctx": {
        "given": "object",
        "permitted": [
          "string"
        ]
      }
    },
    ...
    ...
  ]
}
```
Is there some problem with using Unions and Literals in conjunction that causes this error?

**Comment by dmontagu** [comment] 2020-01-29 01:45
It's not clear what you think is the error, here, but I believe what is happening is that, when you have a Union fail to parse, it tells you why it failed for each of the possible cases.

In particular, it doesn't make use of a Literal field as a discriminator to reduce the set of errors it returns -- it will tell you for each of the other possible union cases why it can't be that, and then it will tell you why it can't be the one with the correct discriminator.

But I don't believe this is a bug.

-----

This could likely be addressed with a better `DiscriminatedUnion` class.

**Comment by sammaphey** [comment] 2020-01-29 18:22
To clarify: If my pydantic model matches that given above and I attempt to create an instance of that model like so
```py
SchemaData(properties={"thing": {"type": "strin", "widget": "default", "description": "desc"}}, order=[], required=[])
```
Then I receive this in response
```py
pydantic.error_wrappers.ValidationError: 20 validation errors for SchemaData
properties -> thing -> type
  unexpected value; permitted: 'string' (type=value_error.const; given=strin; permitted=('string',))
properties -> thing -> widget
  unexpected value; permitted: 'reference' (type=value_error.const; given=default; permitted=('reference',))
properties -> thing -> type
  unexpected value; permitted: 'array' (type=value_error.const; given=strin; permitted=('array',))
properties -> thing -> widget
  unexpected value; permitted: 'list' (type=value_error.const; given=default; permitted=('list',))
properties -> thing -> items
  field required (type=value_error.missing)
properties -> thing -> type
  unexpected value; permitted: 'string' (type=value_error.const; given=strin; permitted=('string',))
properties -> thing -> widget
  unexpected value; permitted: "alias='any' extra={}" (type=value_error.const; given=default; permitted=("alias='any' extra={}",))
properties -> thing -> accepted_types
  field required (type=value_error.missing)
properties -> thing -> type
  unexpected value; permitted: 'object' (type=value_error.const; given=strin; permitted=('object',))
properties -> thing -> widget
  unexpected value; permitted: 'dictionary' (type=value_error.const; given=default; permitted=('dictionary',))
properties -> thing -> properties
  field required (type=value_error.missing)
properties -> thing -> required
  field required (type=value_error.missing)
properties -> thing -> order
  field required (type=value_error.missing)
properties -> thing -> type
  unexpected value; permitted: 'string' (type=value_error.const; given=strin; permitted=('string',))
properties -> thing -> widget
  unexpected value; permitted: 'date' (type=value_error.const; given=default; permitted=('date',))
properties -> thing -> type
  unexpected value; permitted: 'boolean' (type=value_error.const; given=strin; permitted=('boolean',))
properties -> thing -> widget
  unexpected value; permitted: 'boolean' (type=value_error.const; given=default; permitted=('boolean',))
properties -> thing -> type
  unexpected value; permitted: 'number' (type=value_error.const; given=strin; permitted=('number',))
properties -> thing -> widget
  unexpected value; permitted: 'number' (type=value_error.const; given=default; permitted=('number',))
properties -> thing -> type
  unexpected value; permitted: 'string' (type=value_error.const; given=strin; permitted=('string',))
```
My expectation is that I would get a singular error stating that the given value of `strin` does not match any of the `Literal` values I specified in `SchemaReferenceType`, `SchemaObjectType`, etc.

Instead I get errors specifying that `properties`, `required`, and `order` are missing on the `thing` field (even though they are not required).

**Comment by dmontagu** [comment] 2020-01-31 01:51
Yes, for each type in the `Union`, it is telling you all the errors that you would get if you try to parse the value as that type. Since there are so many possible types of values for the `properties` dict, you get a lot of errors.

-----

If you think something else is going wrong, please make a self-contained example demonstrating the behavior, and also share precisely the text you think should be output as part of the error message.

The example you are sharing is hard to discuss because of how complex it is, and because it can't be reproduced (since you've only shared the code for some of the types).

**Comment by samuelcolvin** [comment] 2020-02-01 15:36
duplicate of #619

**Closed by samuelcolvin** 2020-02-01 15:36 UTC
Labels: bug
