### ISSUE TITLE
Class attributes starting with underscore do not support assignment

### ISSUE THREAD

**Issue by dmfigol** [samuelcolvin/pydantic#288] opened 2018-10-30 21:44 UTC
# Bug

For bugs/questions:
* OS: **macOS**
* Python version `import sys; print(sys.version)`: **3.6.6**
* Pydantic version `import pydantic; print(pydantic.VERSION)`: **0.14**

In #184 it was suggested to use variables starting with the underscore, however this does not work.
The last comment in #184 referred to the same problem, but it is technically a separate issue.

```py
from pydantic import BaseModel
m = BaseModel()
m._foo = "bar"
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/dmfigol/projects/my/public/simple-smartsheet/.venv/lib/python3.6/site-packages/pydantic/main.py", line 176, in __setattr__
    raise ValueError(f'"{self.__class__.__name__}" object has no field "{name}"')
ValueError: "BaseModel" object has no field "_foo"
```

**Comment by samuelcolvin** [comment] 2018-11-15 10:53
(I've updated the issue title to better reflect the issue).

Personally, I don't think it's that important, but if you'd like the feature, I'd be happy to accept a PR.

**Comment by asemic-horizon** [comment] 2019-04-22 19:02
I'm having this same problem in a non-workaroundable context. Can someone maybe give some context into why there is this restriction and if there's any way to hack around it, even if ugly?

**Comment by samuelcolvin** [comment] 2019-04-22 19:08
Have you tried using [field aliases](https://pydantic-docs.helpmanual.io/#model-config)?

eg,

```py
class MyModel(BaseModel):
    foobar: str
    class Config:
        fields = {'foobar': '_foobar'}
```

**Comment by asemic-horizon** [comment] 2019-04-22 19:34
That works in a small example
```
import json, my_models

with open('test.json') as f: d = json.load(f)
model = my_models.MyModel(**d)
````

I continue to have problems from the context of FastAPI. That's not the beginning of a new question, it's for the next person to arrive here from Google.  

Thanks for your help!

**Comment by edatpb** [comment] 2019-05-30 09:27
> That's not the beginning of a new question, it's for the next person to arrive here from Google.
👋 Oh hi!
@asemic-horizon Did you find a solution or a good workaround yet? I'll post again if I find one

**Comment by asemic-horizon** [comment] 2019-05-30 13:25
Yeah sorry. 

As I had said, field aliases worked in small toys examples but didn't seem to work in a larger app context, which made me suspect the problem was at FastAPI itself and therefore not pertinent to this issue.

After further rounds of research and bug squashing, minor and subtle errors on my end (my code on top of FastAPI) surfaced. By then I had forgotten I had gone to Pydantic support for it. 

Thanks everyone!

**Comment by asemic-horizon** [comment] 2019-05-30 13:28
(On my end I would "vote this issue closed" or its equivalent in the github issue tracker. I suspect I can't because I didn't actually open it.)

**Comment by samuelcolvin** [comment] 2019-05-30 13:45
I'm pretty user aliases work fine in fastapi.

Closing, but if someone really wants this, let me know and I can reopen it.

**Comment by tiangolo** [comment] 2019-06-03 15:26
@asemic-horizon field aliases work normally in FastAPI and are even documented/recommended in several places.

If you still have issues with them, feel free to open an issue in FastAPI with the minimum sample to reproduce your issue: https://github.com/tiangolo/fastapi/issues/new/choose

**Comment by bartekbrak** [comment] 2019-06-26 02:00
I read the above but saw no explanation for this limitation. From brief study of the source code I could not determine any danger in sunder fields. 

This check is introduced in the first commit ever a8e844da and a check added in f9cf6b42 but no explanation given in commit messages. 

Python itself by design does not enforce any special meaning to sunder and dunder fields - the "we are all consenting adults here" approach. I am used to a convention of marking fields private-like with sunder. 

I would  very much like to know the motivation or changing this.

**Comment by pdonorio** [comment] 2019-12-07 18:41
Hello there,  I use pydantic in FastAPI as well, and I use mongodb as database.

Mongo sets Identifiers as the field `_id` in collections/query outputs and handling those via Pydantic models is quite confusing because of this issue. Let me try to show what I do to ask if I'm doing something wrong; situations I've met with my use case

1. when sending the id as output I have to create a Model with the alias as

```python
class Foo(BaseModel):
    id: str = Field(..., alias='_id')
    ...

query = db.collection.find(...)
validated = Foo(**query).dict()
# where validated = {'id': MONGO_HASH, ...}
# send validated as response
```
Note: if I'd want to send the id like mongo does (if my API are used by another service that deals with queries and mongo for example) I need to use 
```python
validated = Foo(**query).dict(by_alias=True)
# where validated = {'_id': MONGO_HASH, ...}
```

2. when storing a PUT in the database the above require the input to be using `id` instead of `_id` like:
```python
data = {'id': EXISTING_MONGO_HASH}
db.collection.update(Foo(**data).dict(by_alias=True))
```
but if some other service is sending me raw data I would get the `_id` in input so I need to change the model to
```python
class Foo(BaseModel):
    id: str = Field(..., alias='_id')
    ...
    class Config:
        allow_population_by_field_name = True
```
otherwise I get a validation error

--- 

There are other situations that I can't recll exactly enough to show by code, 
but in general I'm currently forced by pydantic since the underscores are not accepted.
I don't feel like using the `id` translation at all, I'd go with `_id` always, because I'm risking non deterministic behaviour in models wrapper methods in the codebase and in the responses.

Hope this helps to reason on it, but thanks for this awesome library!

**Comment by gpakosz** [comment] 2020-02-07 16:07
Hello @samuelcolvin 👋

I just started using `pydantic` along with `FastAPI` and `pymongo`. I used `alias` like @pdonorio mentions above. But I would like to understand why attributes starting with underscore are disallowed in the first place?

**Comment by samuelcolvin** [comment] 2020-02-07 18:57
I still think most python users would not expect "private" attributes to be exposed as fields.

I know python doesn't formally prevent attributes who's names start with an underscore from being accessed externally, but it's a pretty solid convention that you're hacking if you have to access attributes with leading underscores. (Yes I know there are some exceptions, but in the grand scheme they're rare).

In the example quoted above regarding mongo, I would personally feel it's inelegant design to keep the mongo attribute `_id` in python with the same name. You should be able to use an alias generator and a shared custom base model to change the field name in all models without repeated code.

Still, if people really want this, I'd accept a PR to allow field names with underscores. I guess the best solution would be to add a new method to `Config` which replaces [this](https://github.com/samuelcolvin/pydantic/blob/6914410f383367964279f1ee02e5abced1d79924/pydantic/main.py#L193-L197) logic, perhaps returning `None` to fallback to the default logic. 

Then in v2 we can completely remove `Config.keep_untouched` it's a bad name and a confusing attribute.

---

None of my business, but: @gpakosz, unless i'm missing something, you're using a synchronous library for io (pymongo) while using an async web framework (starlette+fastapi). I would worry that your entire process will hang during every database call, thereby negating the point in asyncio.

**Comment by Garito** [comment] 2020-02-08 19:29
I'm agree that, in python, underscore variables are considered private, so I understand your point
But
everyone that uses mongodb (perhaps others) must flow our code with by_alias=True which is not that bad (but talking about elegance seems very weird)
The problem becomes deeper when you use lists of pydantic models
Then you must add a good amount of extra fors to return the information in the correct way (for read and write)

What about a config attribute like always_by_alias = True?

**Comment by samuelcolvin** [comment] 2020-02-09 17:53
You can just implement your own custom base model and overwrite `.dict()` to have `by_alias=True` default.

I don't want to add more config options unless absolutely necessary. Also it would be weird since I think `.dict()` and `.schema()` have different defaults.

Perhaps we can change the default to True in V2 once we have load and dump aliases.

**Comment by samuelcolvin** [comment] 2020-02-10 11:15
Allowing fields with underscores would also conflict with #1139.

**Comment by mortbauer** [comment] 2020-03-22 17:36
I'm very new to pydantic, however i'm really impressed and really like it, however with the current implementation filtering out any field starting with an underscore which is completely unconfigurable [main.py 162](https://github.com/samuelcolvin/pydantic/blob/d495710303c7716f0a54281b86a7c1c81930c223/pydantic/main.py#L162)
except monkey patching is not really acceptable. So I think it is really necessary to add an additional configuration parameter.

**Comment by Seshirantha** [comment] 2020-03-31 04:01
Same thing happens in connexion framework. I want to use default mongo _id as the id.
````python
class ConfigurationFileMetadata(BaseModel):
    _id: str
    files: List[FileMetadata]
    type: str
    network_element_name: str
    created_date: str
````
Set id
````python
data = ConfigurationFileMetadata.parse_obj(info.to_dict())
data._id = my_custom_id
````
Error
````
ValueError: "ConfigurationFileMetadata" object has no field "_id"
````

**Comment by samuelcolvin** [comment] 2020-03-31 08:54
Better to use an alias for that field.

**Comment by StephenBrown2** [comment] 2020-03-31 13:56
For the pymongo issue specifically I moved to mongoengine, which exposes `_id` as `id`. No more need for aliasing!

**Comment by iyedg** [comment] 2020-04-30 12:01
The solution for me was using aliases and `by_alias` when exporting the model. Using the example from @Seshirantha that would look as follows:

```python
class FileMetadata(BaseModel):
    id: str = Field(alias="_id") # can be done using the Config class
    created_date: str

input_data = {"_id": "some id", "created_date": today()}
FileMetadata(**input_data).dict(by_alias=True)
```
That should return ` {"_id": "some id", "created_date": "whatever today is"}`

I am using Pydantic with pymongo therefore having access to `_id` and `_meta` on the validated model is very important.

**Comment by killswitch-GUI** [comment] 2020-05-14 22:06
+1 on this, would be a nice feature. Ill use alias in the meantime but this for sure caught me off-guard.

**Comment by mortbauer** [comment] 2020-05-17 06:48
I earlier thought I needed that feature, and also found a quite easy way to have it via monkey patching:
`
# monkey patch to get underscore fields
def is_valid_field(name:str):
    if not name.startswith('__'):
        return True
    elif name == '__root__':
        return True

pydantic.main.is_valid_field = is_valid_field
`
However I have to say that using an alias works very well now for me!

**Comment by PrettyWood** [comment] 2020-07-23 12:42
#1679 would probably be a good solution

**Comment by aolefira** [comment] 2020-09-10 05:54
+1, "allowing fields with underscores" is necessary for mongodb issue. Using aliases is just workaround  and not very handsome

**Comment by 153957** [comment] 2020-09-10 11:20
+1 – Also fields starting with `_` are also useful for ArangoDB, each vertex object there has a `_key`, `_id`, and `_rev`, and edges also have `_from` and `_to`.

**Comment by GDYendell** [comment] 2020-09-21 16:05
I am finding that I can't set attributes starting with underscore internally (via `self.`), not just externally. Is this a separate issue?

**Comment by PrettyWood** [comment] 2020-11-04 10:08
Hello,
Should we close this issue now that [private model attributes](https://pydantic-docs.helpmanual.io/usage/models/#private-model-attributes) have been implemented?

```python
from pydantic import BaseModel, PrivateAttr

class Model(BaseModel):
    _foo = PrivateAttr('')

m = Model()
print(repr(m._foo))  # ''
m._foo = 'foo'
print(repr(m._foo))  # 'foo'
```

**Comment by AntonOvsyannikov** [comment] 2020-11-08 21:18
Sorry, in which version `underscore_attrs_are_private` are implemented? I use 1.7.2 and still have error while using private attributes:

```
import pkg_resources
print(pkg_resources.get_distribution("pydantic").version)

from pydantic import BaseModel

class Model(BaseModel):
    _foo: int
    class Config:
        underscore_attrs_are_private = False

m = Model(_foo=2)
print(m, m._foo)

```

```
1.7.2
Traceback (most recent call last):
  File "/Users/aovsyannikov/Library/Application Support/JetBrains/PyCharm2020.2/scratches/scratch_139.py", line 14, in <module>
    print(m, m._foo)
AttributeError: 'Model' object has no attribute '_foo'
```

**Comment by 153957** [comment] 2020-11-09 07:27
Apparently with the new private (`underscore_attrs_are_private`) implementation, you can still not provide the values during initialization of the class. Moreover, the values are not included in the `.dict()` output.

```
class Model(BaseModel):
    _id: str = None

    class Config:
        underscore_attrs_are_private = True


x = Model(_id='a/123')
# Model()
x._id
# None
x._id = 'a/123'
x
# Model()
x._id
# 'a/123'
x.dict()
# {}
```
If I include `extra = 'forbid'` in the `Config` it forbids including `_id` when making the model, it can still be assigned after making the model, but is still not included in the dict output.

**Comment by AntonOvsyannikov** [comment] 2020-11-09 12:25
Ok, thanks, clear. Just copy there my comment to #2101 
Now, been having the Config for such attributes it seems quite artificial limitation to ignore sunder attributes (which is only private in Python world, and widely used outside), so it brings lot of inconvenience when work with models for MongoDB i.g. Suppose more flexible config is required, like sunder_attributes : Literal['normal', 'ignored', 'private']. I will risk opening a new feature request.

**Comment by MrMrRobat** [comment] 2020-11-09 12:42
@153957, @PrettyWood, just to make it clear: `underscore_attrs_are_private` and private attributes themselves are not meant to be used as fields. They're meant to be internally implemented and used only inside of model class, not anywhere outside.

**Comment by 153957** [comment] 2020-11-09 13:11
Understood, however, for my usage with ArangoDB the issue remains that there are some 'normal/valid' fields which start with a single underscore that should be included in the output of `dict()`. For now I am using something similar to the monkey patch [suggested by mortbauer](https://github.com/samuelcolvin/pydantic/issues/288#issuecomment-629752056).

**Comment by emremrah** [comment] 2020-11-23 18:31
I have just tried a workaround like this to issue the data model to MongoDB using `.dict()` method:
```python
class A(BaseModel):
    _id = 5
    
    def dict(self):
        d = super.dict()
        d['_id'] = d['id']
        del d['id']
        return d
```
When I call `A().dict()`, it gives an error:  `AttributeError: type object 'super' has no attribute 'dict'`. But `BaseModel` has a dict method. I'm probably missing some Python feature. Can someone enlight me why this is not working? Thanks.

**Comment by PrettyWood** [comment] 2020-11-23 18:33
Hey @emremrah
Probably because you want to call `super()` not `super` ;)

**Comment by emremrah** [comment] 2020-11-23 18:38
> Hey @emremrah
> Probably because you want to call `super()` not `super` ;)

Ahh you are right @PrettyWood ,:
```python
class A(BaseModel):
    id = 5
    
    def dict(self):
        d = super().dict()
        d['_id'] = d['id']
        del d['id']
        return d
```
returned `{'_id': 5}`. So if anyone is interested. I just have to call `.dict()` method when inserting to MongoDB. But initiating `A` with a MongoDB document still won't work as we wanted.

**Comment by PrettyWood** [comment] 2020-11-23 18:48
@emremrah Using alias `id = Field(5, alias='_id')` should work 👍

**Comment by emremrah** [comment] 2020-11-23 18:55
@PrettyWood Yep, I just have to be careful to use `.id` and not `._id` in code. Thank you!

**Comment by samuelcolvin** [comment] 2020-11-23 21:38
Thanks @PrettyWood, closed.

**Closed** 2020-11-23 21:38 UTC
Labels: feature request, help wanted

**Comment by mikegrima** [comment] 2021-04-15 23:04
I have a use case that is kind of the opposite of what others are doing. Effectively, I have a use case where the raw input needs to be processed or fetched lazily and then cached. In my case, if a value is absent, then I need to make an API call to a remote system to fetch the data.

I need to load the raw value that arrives and keep it in a private member (something prefixed with an underscore `_`). Users will access a `property` of the class which will do the needful to ensure that a proper value is returned. 

Here is what I am trying to do:

```python
class SomeThing(BaseModel):

    some_field: str = Field(..., alias="someField")
    some_other_field: str = Field(..., alias="someOtherField")

    # Lazy-loading fields if they are absent
    _lazy_field: Optional[Dict[str, Any]] = Field(..., alias="lazyField")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self._all_loaded = self._lazy_field != None

    def _lazy_load():
        # reach to to external API...
        # self._lazy_field = processed result from API...
        self._all_loaded = True

    @property
    def lazy_field():
        if not self._all_loaded:
            self._lazy_load()
        
        return self._lazy_field
```

Unfortunately, this does not work, because fields that are prefixed with an underscore are ignored. In order to make this work, I need to scrap the underscore on the field (make the field named `raw_lazy_load` or something equivalent). I would prefer to keep with the "expected" Python behavior and have it underscored to indicate that you should not directly access that field.

I tried the other `class Config` options mentioned in the thread, but don't work for me. If it's easy to fix, I'm happy to submit a PR for it.

**Comment by frndlytm** [comment] 2022-01-25 18:25
Yeah, second all the _attribute support. it's not just Mongo, any Elasticsearch work behind FastAPI misses out on the meta-properties on documents. any in general as a DB developer, I find _attributes an expressive way of working around langue-specific keywords when necessary, like _id and _timestamp

to me, it seems like a by_alias workaround, while sufficient to solve any immediate issues, is not expressing the schema being parse.

It seems that the justification for why it's not supported is because Python relies on underscores for privacy problems, but I would argue that Python metaclasses being a way of having the language rewrite itself throws that issue out the window, particularly in their use in `pydantic`.

Additionally, I would ask what is the core responsibility or value proposition of pydantic, which I believe is as a model parsing library with applications in messaging applications. (e.g. there's nothing stopping a protobuf loader in the Model Config),a and if that IS the value proposition, then the BaseModel declaration should look as close as possible to the model being parsed.

so really, any restrictions on identifiers that aren't explicitly prohibited by the python language (like `@timestamp`), should probably be supported natively.

Just my two cents.

**Comment by jtfidje** [comment] 2022-02-08 09:24
Yea we also really need this for use with ArangoDB.

**Comment by emremrah** [comment] 2022-03-03 09:34
So I've been working on this. What I needed is to easily cast between ObjectId and str to save to MongoDB or return data to frondend.

To keep things simple on the frontend, object ids are strings; not Objects with "$oid" key in it.

So I implement my data models like this:
```py
# to cast strings to object id for incoming data, especially from frontend
class MongoObjectId(ObjectIdStr):
    "Cast string to ObjectId."""
    @classmethod
    def __get_validators__(cls):
        yield cls.validate

    @classmethod
    def validate(cls, v):
        if bson.ObjectId.is_valid(v):
            return bson.ObjectId(v)
        raise ValueError(f'{v} is not a valid ObjectId for type {cls}')

def oidstr(d):
    """Recursively search for values that objectids and convert them to strings."""
    if isinstance(d, dict):
        return {k: oidstr(v) for k, v in d.items()}
    if isinstance(d, list):
        return [oidstr(v) for v in d]
    if isinstance(d, bson.ObjectId):
        return str(d)
    return d

class MyModel(BaseModel):
    person_id: MongoObjectId

    def dict_with_str(self, *args, **kwargs):
        """Dump the model to a dict and convert ObjectIds to str."""
        # use the default dict method
        d = super().dict(*args, **kwargs)

        # recursively convert ObjectIds to str
        d = oidstr(d)

        return d
```

I don't know if I'm overcomplicating things while trying to keep it simple for front end. Please share your thoughts. Thank you.

**Comment by lgvld** [comment] 2022-04-05 22:38
As @frndlytm said: 

> so really, any restrictions on identifiers that aren't explicitly prohibited by the python language (like @timestamp), should probably be supported natively.

Regardless of the underlying database, Pydantic should not enforce what is only a convention. This is not an expected behavior.

**Comment by Bi0max** [comment] 2022-10-30 11:05
> I still think most python users would not expect "private" attributes to be exposed as fields.
> 
> I know python doesn't formally prevent attributes who's names start with an underscore from being accessed externally, but it's a pretty solid convention that you're hacking if you have to access attributes with leading underscores. (Yes I know there are some exceptions, but in the grand scheme they're rare).
> 
> In the example quoted above regarding mongo, I would personally feel it's inelegant design to keep the mongo attribute `_id` in python with the same name. You should be able to use an alias generator and a shared custom base model to change the field name in all models without repeated code.
> 
> Still, if people really want this, I'd accept a PR to allow field names with underscores. I guess the best solution would be to add a new method to `Config` which replaces [this](https://github.com/samuelcolvin/pydantic/blob/6914410f383367964279f1ee02e5abced1d79924/pydantic/main.py#L193-L197) logic, perhaps returning `None` to fallback to the default logic.
> 
> Then in v2 we can completely remove `Config.keep_untouched` it's a bad name and a confusing attribute.
> 
> None of my business, but: @gpakosz, unless i'm missing something, you're using a synchronous library for io (pymongo) while using an async web framework (starlette+fastapi). I would worry that your entire process will hang during every database call, thereby negating the point in asyncio.

I also need a possibility to use underscore attributes.
As @samuelcolvin suggested himself, the easiest way would be probably to implement a simple switch in the Config, which would allow to use "_attribute" style.
Is it something that you would accept in PR?

**Comment by fernando-freitas-alves** [comment] 2022-11-18 20:49
Maybe this helps:

```python
class PrivateInitBaseModel(BaseModel):
    """
    Workaround for initializing models by specifying their private attributes
    """

    def __init__(self, **data: Any) -> None:
        for private_key in self.__class__.__private_attributes__.keys():
            try:
                value = data.pop(private_key)
            except KeyError:
                ...
            finally:
                setattr(self, private_key, value)
        super().__init__(**data)
```

**Comment by Pedrexus** [comment] 2023-02-23 01:18
Can the original question be solved in any way? I tried using alias, but still `model._foo = False` raises the same error.

**Comment by tumma72** [comment] 2023-03-05 16:00
I have just started to use Pydantic in a couple of applications I am working on at the moment. The issue I am facing, which is probably related to the design I am using is the following:

1. I have created a series of Pydantic BaseModel classes, with a shared MyBaseModel, which are converting and validating data coming from a remote server API. The validation works, I am able to test it with a series of mock data and also live data, they behave as expected. So I was very happy with Pydantic till this point 😉
2. I need to integrate the data models into application models, I am not using FastAPI but just my own python application. What I mean with this, is that I have for example a Market(MarketBaseModel, AutoLogger) which does a classical mixin between the Pydantic model and the AutoLogger class which adds distributed logging features. The AutoLogger adds a local self.__logger attribute to the Market class, and getter and setter properties for the logger. 

The problem I am facing is that no matter how I call the self.__logger, or self._logger or self.__logger__ attribute, even if it is initialized in the __init__ method and it isn't declared as a class attribute, because the MarketBaseModel is a Pydantic Model, extends the validation not only at the attributes defined as Pydantic attributes but also to every other attribute which is declared in __init__. Now I might be thinking too complicated, and surely I could use composition and pass a logger instance to the constructor of the Market, but that would cause to add a lot of boiler plate code that I want to avoid at least at the high level APIs. Any idea on how I can still inherit from a Pydantic BaseModel while having arbitrary defined instance attributes?

**Comment by dmontagu** [comment] 2023-03-06 16:14
I'm thinking it might be possible to do something with `keep_ignored`, and setting an attribute on the class to a type in that. 

More explicitly, you should be able to do something like:
```python
class MyModel:
    a: int
    b: str  # whatever, random fields

    logger = MyLogger()

    class Config:
        ...
        keep_untouched = (MyLogger,)
```

Any chance this approach might work for you?

**Comment by aolefira** [comment] 2023-03-09 05:30
> I'm thinking it might be possible to do something with `keep_ignored`, and setting one of the attributes on the class to have a value that is a type in that setting.
> 
> More explicitly, you should be able to do something like:
> 
> ```python
> class MyModel:
>     a: int
>     b: str  # whatever, random fields
> 
>     logger = MyLogger()
> 
>     class Config:
>         ...  # whatever other values you want to set on the Config
>         keep_untouched = (MyLogger,)
> ```
> 
> Any chance this approach might work for you?

logger is not seems to be public variable. use __logger instead

**Comment by tumma72** [comment] 2023-03-09 09:08
Thanks for your suggestions, It appears I have managed to solve this problem at least at the moment, by changing the design and going for composition instead of inheritance. So I have now my model classes which have a class attribute called schema_class which is type bound to my schema superclass (a Pydantic BaseModel extension) and they have a from_data and to_data methods, which allows to read the serialized structure, validate the model using the schema_class, and store it as data storage as self.data into the model class. With the composition design I have also managed to create a PersistenceEnabled mixin which allow me to extend the main Model with SQLAlchemy persistence, using the same pattern, by declaring a db_class class attribute, and providing saving, loading and searching features on the model. This of course requires to have 3 classes implemented:
1. The main domain related Model class (e.g.: MyModel) which now can mixin with all other regular python classes;
2. The Pydantic schema class (e.g.: MyModelSchema) which does all of the validation and serialization business;
3. If the domain model needs persistence also a db class (e.g.: MyModelDB) which does all of the CRUD business behind the scenes, and allows also for transaction participation (in case of multiple items operation).

I didn't really solve the problem, but I went around it. Every piece is smaller, has clearer responsibilities and doesn't cause interference between the different frameworks.

**Comment by rreusser** [comment] 2023-03-27 18:42
I could be misunderstanding something, but I'm completely confused about how to work around this, as it seems to break private attrs, even for private usage. I'm using version `pydantic@1.10.6` on `python@3.8.16` and find private variables completely unusable.

I think in my case all I want is for a private variable to be perfectly, completely unknown to pydantic. Is there really no way to accomplish this? (Whether this is indicated by virtue of it being underscored or explicitly declared as unhandled by pydantic is pretty irrelevant to me.)

```python
from pydantic import BaseModel

class Foo(BaseModel):
    _flag: bool = True

    def perform_action(self):
        self._flag = False
    

foo = Foo()
foo.perform_action()
```

Raises:

```
Traceback (most recent call last):
  File "test.py", line 12, in <module>
    foo.perform_action()
  File "test.py", line 7, in perform_action
    self._flag = False
  File "pydantic/main.py", line 357, in pydantic.main.BaseModel.__setattr__
ValueError: "Foo" object has no field "_flag"
```

**Comment by tommyjcarpenter** [comment] 2023-07-21 12:29
Sorry if I am being naive here, but after reading this thread, I came across this: https://docs.pydantic.dev/latest/usage/models/#private-model-attributes

This seems to solve this problem?

```
class Foo(BaseModel):
    class Config:
        extra = Extra.forbid

  bar: date
  __myvar__ = PrivateAttr(...)
```

**Comment by rreusser** [comment] 2023-07-21 14:28
@tommyjcarpenter I believe pydantic v2 was just released, and it looks like the diff in that code block is:

```python
# v1.1:
    _secret_value: str = PrivateAttr()

# v2:
    _secret_value: str
```

so maybe it's that `PrivateAttr` is the default behavior for underscored attributes so that you don't explicitly need to specify? Not certain if there are differences beyond that.

**Comment by tommyjcarpenter** [comment] 2023-07-21 14:42
@rreusser sorry I don't follow - just saying, I used PrivateAttr and it seemed to solve all the commotion in this thread.

**Comment by rreusser** [comment] 2023-07-21 15:13
Oh, sorry, I misread! Disregard. I've done the same, but I'm on v1.1 still, and when I clicked the above link I noticed that maybe this has changed slightly in v2.
