### ISSUE TITLE
Parsing behaviours with parse_obj

### ISSUE THREAD

**Issue by Gatux** [samuelcolvin/pydantic#2160] opened 2020-11-30 12:43 UTC
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
pydantic version: 1.7.2
pydantic compiled: True
python version: 3.8.5
platform: Linux-4.15.0-118-generic-x86_64-with-glibc2.2.5
optional deps. installed: ['typing-extensions']
```

`parse_obj` uses `dict()` built-in method and because of that some weird parsing behaviors can happen when a list is provided as input.

```py
from datetime import datetime

from pydantic import BaseModel

class User(BaseModel):
    firstname: str
    lastname: str = None

User.parse_obj([{'firstname': 'John', 'lastname': None}])  # User(firstname='lastname', lastname=None)

# Because
dict([{'firstname': 'John', 'lastname': None}])  # {'firstname': 'lastname'}
```

**Comment by PrettyWood** [comment] 2020-11-30 13:58
Hello @Gatux 

Well I don't really know what to say. As you say it's based on builtin parsing behaviour.
Did you expect a `TypeError` ?
Or did you expect a list of users in which case you should do
```python
from pydantic.tools import parse_obj_as

parse_obj_as(List[User], [{'firstname': 'John', 'lastname': None}])
# [User(firstname='John', lastname=None)]
```

**Comment by samuelcolvin** [comment] 2020-11-30 23:40
duplicate of #1268 I think

**Closed by samuelcolvin** 2020-11-30 23:40 UTC
Labels: bug

**Comment by Gatux** [comment] 2020-12-01 08:22
Sorry for the duplicate, indeed #1268 is link to the same problem with `dict()`. Missed that one.

@PrettyWood: with my example, it should raise a ValidationError as stated in the documentation:
https://pydantic-docs.helpmanual.io/usage/models/#helper-functions
```
[...] If the object passed is not a dict a ValidationError will be raised.
```

And you're right, it becomes a real problem when I'm trying to parse `Union[User, List[User]]`, which fails with my example.
For now I'm using this workaround: `Union[List[User], User]`.
As this behavior was quite unexpected for me, I thought it would be useful to exposed it here.

**Comment by PrettyWood** [comment] 2020-12-23 09:49
I opened #2211 to make the `dict_validator` strict  (i.e. stop doing `try: dict(obj) ...`)
https://github.com/samuelcolvin/pydantic/blob/3496a473c73156fb02edf7dd8a1b1617a76a1b60/pydantic/validators.py#L216-L219
But it doesn't concern this exact same behaviour in `parse_obj`
https://github.com/samuelcolvin/pydantic/blob/3496a473c73156fb02edf7dd8a1b1617a76a1b60/pydantic/main.py#L515-L519
Don't know if it should be tackled in its own PR or in this one but it's just to note it's not the exact same issue
