### ISSUE TITLE
validate_assignment / allow_mutation not working properly with individual list elements

### ISSUE THREAD

**Issue by KraxelHuber** [samuelcolvin/pydantic#2328] opened 2021-02-08 12:15 UTC
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug
pydantic version: 1.7.3

I am trying to make use of ``validate_assignment`` and ``allow_mutation`` flags.  
My model checks for a ``List[int]``. When changing the whole `list` after instantiation, everything works as expected, i.e. either the ``list`` will get validated or ``pydantic`` prevents me from changing the ``list`` after instantiation.  

However, If I change individual list elements only, ``validate_assignment`` and ``allow_mutation`` seems to have no effect at all.

```
from typing import List

from pydantic import BaseModel


class Conf(BaseModel):
    x: List(int)

    class Config:
        # No matter which one you choose, it has no effect
        validate_assignment = True
        # allow_mutation = False


foo = Conf(x=[3, 7])

try:
    foo.x[0] = "Test"
    print("Assignment successful. It should be unsuccessful!")
    print(f"New value: {foo.x}")
except ValueError as e:
    print("Assignment failed.")
    print(e)
```

**Comment by PrettyWood** [comment] 2021-02-08 13:15
Hi @KraxelHuber 
It's a duplicate of https://github.com/samuelcolvin/pydantic/issues/496.

**Closed by PrettyWood** 2021-02-08 13:15 UTC
Labels: bug
