### ISSUE TITLE
Pre-validator isn't called for required value

### ISSUE THREAD

**Issue by eigenein** [samuelcolvin/pydantic#412] opened 2019-03-05 17:24 UTC
* OS: macOS 10.14.3
* `3.7.2 (v3.7.2:9a3ffc0492, Dec 24 2018, 02:44:43) [Clang 6.0 (clang-600.0.57)]`
* Pydantic 0.20.1

> the keyword argument `pre` will cause validators to be called prior to other validation

Prior to 0.19.0 this worked for missing required values, but that release seems to break it. Validator doesn't seem to be even called:

```python
In [6]: class Foo(BaseModel):
   ...:     bar: str
   ...:     @validator('bar', pre=True)
   ...:     def validate_bar(cls, value):
   ...:         print('Called')

In [7]: Foo()
---------------------------------------------------------------------------
ValidationError                           Traceback (most recent call last)
...
ValidationError: 1 validation error
bar
  field required (type=value_error.missing)
```

**Comment by samuelcolvin** [comment] 2019-03-05 17:39
duplicate of #387

**Closed by samuelcolvin** 2019-03-05 17:39 UTC

**Comment by samuelcolvin** [comment] 2019-03-05 17:41
also discussed on #411.

Should be fixed soon.
