### ISSUE TITLE
EmailStr special-cases "@example.[org|com]"

### ISSUE THREAD

**Issue by provinzkraut** [samuelcolvin/pydantic#4141] opened 2022-06-07 10:58 UTC
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
         pydantic version: 1.9.0
        pydantic compiled: True
             install path: /home/***/python3.10/site-packages/pydantic
           python version: 3.10.0 (default, Oct 12 2021, 14:07:44) [GCC 9.3.0]
                 platform: Linux-5.13.0-46-generic-x86_64-with-glibc2.34
 optional deps. installed: ['dotenv', 'email-validator', 'typing-extensions']
```

```py
import pydantic

class Foo(pydantic.BaseModel):
    email: pydantic.EmailStr

Foo(email="foo@example.org")
```

The above code will result in a `ValidationError`. IMHO this is not correct though, as this *is* a valid email address, albeit not a usable one. But it's one extensively used, and specifically designed, for testing purposes, and not being able to use a testing domain for testing purposes because pydantic falsely flags this as an "invalid email address" kind of defeats its purpose.

**Comment by samuelcolvin** [comment] 2022-06-08 06:37
Duplicate of #4009.

You need to upgrade or downgrade email-validator.

**Closed by samuelcolvin** 2022-06-08 06:37 UTC
Labels: bug
