### ISSUE TITLE
alias_generator being called with the fields prefixed by "key_" after 1.9

### ISSUE THREAD

**Issue by canassa** [samuelcolvin/pydantic#3661] opened 2022-01-12 10:31 UTC
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.9.0
            pydantic compiled: True
                 install path: .../.venv/lib/python3.9/site-packages/pydantic
               python version: 3.9.5 (default, May 28 2021, 22:15:15)  [Clang 12.0.0 (clang-1200.0.32.28)]
                     platform: macOS-12.0.1-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

This is a self-contained example of the problem:

```py
from typing import Dict, Any

from pydantic import BaseModel

GENERATOR_MAP: Dict[str, str] = {
    "supplementary_data": "SplmtryData",
}

def generator(name: str) -> str:
    return GENERATOR_MAP[name]


class MyModel(BaseModel):
    supplementary_data: Dict[str, Any]

    class Config:
        alias_generator = generator
```

On < 1.9 the example works fine, but on 1.9 it throws the following error:

```
Traceback (most recent call last):
  File "bug.py", line 13, in <module>
    class MyModel(BaseModel):
  File "pydantic/main.py", line 204, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 488, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 419, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 534, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 694, in pydantic.fields.ModelField._type_analysis
  File "pydantic/fields.py", line 776, in pydantic.fields.ModelField._create_sub_type
  File "pydantic/fields.py", line 440, in pydantic.fields.ModelField._get_field_info
  File "pydantic/config.py", line 90, in pydantic.config.BaseConfig.get_field_info
  File "bug.py", line 10, in generator
    return GENERATOR_MAP[name]
KeyError: 'key_supplementary_data'
```

It looks like when the field has a type `Dict` the alias_generator is being called twice, once with the regular field name `supplementary_data` and once with a `key_` prefix.

**Comment by samuelcolvin** [comment] 2022-04-01 18:02
duplicate of #3660

**Closed by samuelcolvin** 2022-04-01 18:02 UTC
Labels: bug
