### ISSUE TITLE
Subclasses of bytes get rejected for `bytes` fields

### ISSUE THREAD

**Issue by MasterKale** [samuelcolvin/pydantic#4023] opened 2022-04-28 18:31 UTC
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.9.0
            pydantic compiled: True
                 install path: /Users/mmiller/Repos/py_webauthn/venv/lib/python3.9/site-packages/pydantic
               python version: 3.9.12 (main, Mar 26 2022, 15:51:15)  [Clang 13.1.6 (clang-1316.0.21.2)]
                     platform: macOS-12.3.1-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

If I attempt to pass in a subclass of `bytes` as the value of a `bytes` field Pydantic rejects it:

```py
from pydantic import BaseModel

class BazzModel(BaseModel):
    bazz: bytes

class BytesSubclass(bytes):
    pass

bazz_instance_2 = BazzModel(bazz=BytesSubclass(b'1234'))
print(bazz_instance_2)
```

```
Traceback (most recent call last):
  File "/Users/mmiller/Repos/py_webauthn/examples/blah2.py", line 9, in <module>
    bazz_instance_2 = BazzModel(bazz=BytesSubclass(b'1234'))
  File "pydantic/main.py", line 331, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for BazzModel
bazz
  Expected bytes, got BytesSubclass (type=type_error)
```
Pydantic tries to coerce values assigned to `bytes` fields to `bytes` via `pydantic.validators.bytes_validator` and `pydantic.validators.strict_bytes_validator`, but the `if isinstance(v, bytes)` returns `v` directly.  I found that if I write a custom `@validator` and return `bytes(v)` instead from a similar `isinstance` check then Pydantic accepts the subclass no problem:

```
from pydantic import BaseModel, validator

class BazzModel(BaseModel):
    bazz: bytes

    @validator('bazz', pre=True)
    def validate_bazz(cls, v):
        if isinstance(v, bytes):
            return bytes(v)
        return v

class BytesSubclass(bytes):
    pass

bazz_instance_2 = BazzModel(bazz=BytesSubclass(b'1234'))
print(bazz_instance_2)  # bazz=b'1234'
```

I think this is a great opportunity to make Pydantic a bit more Pythonic, especially since the plumbing is already in place to perform this value coercion.

**Comment by samuelcolvin** [comment] 2022-05-14 12:03
Duplicate of #3706 (I created this specifically for your webauthn library), fixed in #3707 :smile:.

I'll include the fix in v1.9.1 although technically it's not a 1.9 regression.

---

But please be aware that in pydantic v2, this will break again.

That's a result of converting bytes to a raw `&[u8]` in rust before performing further validation. We can't avoid it by default without switching to a much much slower approach.

I haven't actually implemented `bytes` in pydantic-core yet, but see similar code [here](https://github.com/samuelcolvin/pydantic-core/blob/e50eecc6853047adc478d82b7c2992fdc1a6c3d3/src/input/input_python.rs#L28) for casting bytes to a str.

The solution will be a custom type with custom validation logic, or a decorator as you have above.

**Closed by samuelcolvin** 2022-05-14 12:03 UTC
Labels: bug
