### ISSUE TITLE
Parsing pydantic dataclasses from objects

### ISSUE THREAD

**Issue by aldanor** [samuelcolvin/pydantic#946] opened 2019-10-27 22:09 UTC
(pydantic 1.0, Python 3.6, macOS, conda)

Running the following:

```python
@pydantic.dataclasses.dataclass
class Foo:
    a: int

    def b(self):
        pass

foo = Foo.__pydantic_model__.parse_obj({'a': 1})
print(foo)
print(type(foo).mro())
print(foo.b())
```

results in:

```log
a=1
[<class '__main__.Foo'>, <class 'pydantic.main.BaseModel'>, <class 'object'>]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
      9 print(foo)
     10 print(type(foo).mro())
---> 11 print(foo.b())

AttributeError: 'Foo' object has no attribute 'b'
```

Hmm... why is `BaseModel` in the MRO list? Where did all the attributes like methods of the original type go?.. Is there a better (official?) way to parse dataclasses from objects?

**Comment by dmontagu** [comment] 2019-10-27 22:44
That's because you are working with the `__pydantic_model__`, which is, unsurprisingly, a pydantic model. Calling `parse_obj` on that model returns an instance of that model, not of the dataclass.

The `dataclass` wrapper is meant to give you a class that, besides the presence of the `__pydantic_model__` attribute, has basically the same api as a regular dataclass. So, it doesn't have any methods a regular dataclass wouldn't have (and in particular, you'd have to implement object parsing yourself).

The purpose of the dataclass wrapper is just to get runtime validation of the types going into the dataclass.

**Comment by samuelcolvin** [comment] 2019-10-28 07:44
This is a feature request, not a bug; and a duplicate of #481.

**Closed by samuelcolvin** 2019-10-28 07:44 UTC
Labels: bug
