### ISSUE TITLE
Field.regex will allow an invalid string to pass validation

### ISSUE THREAD

**Issue by kierandarcy** [samuelcolvin/pydantic#1470] opened 2020-05-01 16:04 UTC
# Bug

The `regex` used to validate a string in `pydantic.Field` will allow a string that does not match the given pattern to pass without raising a validation error.

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.5.1
            pydantic compiled: True
                 install path: /home/kieran/projects/bimacademy/buildstream/prototypes/backend-admin/.venv/lib/python3.8/site-packages/pydantic
               python version: 3.8.2 (default, Feb 26 2020, 02:56:10)  [GCC 7.4.0]
                     platform: Linux-4.15.0-99-generic-x86_64-with-glibc2.27
     optional deps. installed: []
```
This simple regex checks for any number of lowercase letters ("a - z") and spaces.

In the example below, the `test="this Should Fail"` should raise a validation error. It does not.  I think this is because it is using `re.match` instead if `re.fullmatch`.

```py
import re
import pydantic

class Test(pydantic.BaseModel): 
    test: str = pydantic.Field(regex="[a-z ]+", description="Allow lower case letters and spaces")

try:
    Test(test="this should pass")
except pydantic.ValidationError:
    print("This should have passed!")

try:
    Test(test="this Should Fail")
except pydantic.ValidationError:
    print("This should have failed!")

assert bool(re.fullmatch("[a-z ]+", "this should pass"))
assert not bool(re.fullmatch("[a-z ]+", "this Should Fail"))

```
Happy to submit a PR! (Looks like a nice easy one)

**Comment by samuelcolvin** [comment] 2020-05-01 16:09
Not a bug, duplicate of #1396.

**Closed by samuelcolvin** 2020-05-01 16:09 UTC
Labels: bug
