### ISSUE TITLE
pylint: No name 'BaseModel' in module 'pydantic' (no-name-in-module)

### ISSUE THREAD

**Issue by darkclouder** [samuelcolvin/pydantic#1961] opened 2020-10-01 06:20 UTC
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and still think this is a bug

# Bug
```
$ pylint main.py --disable=C,W
************* Module main
main.py:1:0: E0611: No name 'BaseModel' in module 'pydantic' (no-name-in-module)

-----------------------------------------------------------------------
Your code has been rated at -40.00/10
```

Output of `python -c "import pydantic.utils; print(pydantic.utils.version_info())"`:
```
             pydantic version: 1.6.1
            pydantic compiled: True
                 install path: /path/to/.env/lib/python3.8/site-packages/pydantic
               python version: 3.8.5 (default, Sep  4 2020, 02:22:02)  [Clang 10.0.0 ]
                     platform: macOS-10.15.4-x86_64-i386-64bit
     optional deps. installed: ['typing-extensions']
```

# Reproduce
main.py:
```py
from pydantic import BaseModel
```

Quick way to reproduce env:
```
mkdir pydantic-pylint
cd pydantic-pylint
echo "from pydantic import BaseModel" > main.py
conda create --prefix ./.env python=3.8 && conda activate ./.env
pip install "pydantic==1.6.1" "pylint==2.6.0"
pylint main.py --disable=C,W
```

**Comment by NazimAli2017** [comment] 2020-10-20 19:41
@darkclouder have been running into this error for a while with Python 3.7, I thought it was just because of Pydantic and its syntax. You can have Pylint ignore it if needed by adding this snippet at the top of the file:
```
# pylint: disable=no-name-in-module
# pylint: disable=no-self-argument
```

**Comment by JFitzy1321** [comment] 2020-11-17 23:20
I'm also getting this error when using Python 3.9 and pylint 2.6.0

**Comment by PrettyWood** [comment] 2020-11-18 00:05
Hey guys,
I can reproduce but the issue [comes from `pylint`](https://github.com/PyCQA/pylint/issues/1524), not `pydantic`!
I guess you just need to add `pydantic` in the whitelist to make `pylint` build an AST from the live module

```bash
▶ pylint --extension-pkg-whitelist='pydantic' main.py

--------------------------------------------------------------------
Your code has been rated at 10.00/10
```
If it solves your problem for all of you I'll close this issue!

**Comment by deweypotts** [comment] 2020-12-11 21:37
Did not solve the issue for me. It says I have a syntax issue at the 2:0
![image](https://user-images.githubusercontent.com/46010392/101957297-6b99d200-3bbe-11eb-80a7-cd32714c89a4.png)

**Comment by dylanvr** [comment] 2020-12-11 22:10
¿El problema no me ha sido resuelto?
![isues](https://user-images.githubusercontent.com/47459841/101959668-beca4f80-3bd3-11eb-8ec3-4515322e3359.jpg)

**Comment by GaelFG** [comment] 2020-12-18 08:51
The workaround by @NazimAli2017 works but disable some pylint feature for the concerned file. (it's fine thought).

*Note :* the following remark havn't been tested, I'm a Python beginner trying it for a side project, I encountered the problem following a FastApi tutorial : https://fastapi.tiangolo.com/tutorial/sql-databases/. 

Since pylint is widely used maybe consider adding an __init__.py file in the pydantic module ? 

The warning is evoked in this stackoverflow question : 
https://stackoverflow.com/questions/40334643/no-name-in-module-error-from-pylint

The official documentation link : 
https://docs.python.org/3/reference/import.html#regular-packages

**Comment by wozniakty** [comment] 2021-01-12 17:56
+100 to getting this fixed.  I think it's important to consider this from the perspective of enterprise organizations who are afraid to move to newer better libraries, having to comment a pylint exception everywhere pydantic is used is raising a lot of unnecessary red flags for my org.

**Comment by samuelcolvin** [comment] 2021-01-12 20:28
> Since pylint is widely used maybe consider adding an __init__.py file in the pydantic module ?

It already exists, is there a particular problem with it?

---

@wozniakty I'd love to fix this and support pylint more. Please research the problem and develop a fix, I'd be very happy to review a PR.

**Comment by bodograumann** [comment] 2021-01-13 15:27
This is a common problem with binary extensions. The pylint official stance is, that you need to add the following to `.pylintrc`:

```
[MASTER]
extension-pkg-whitelist=pydantic
```
Cf: https://github.com/PyCQA/pylint/issues/1524#issuecomment-508934142

I guess if you want to automate this, you need to extend pylint. This is not something which should be handled in individual modules.

**Comment by samuelcolvin** [comment] 2021-01-13 15:34
Thank you so much @bodograumann 

Closing this issue.

**Closed by samuelcolvin** 2021-01-13 15:34 UTC
Labels: bug

**Comment by TheCleric** [comment] 2021-02-26 14:18
For anyone else with this issue I was also able to solve by simply changing my import from:

`from pydantic import BaseModel`

to

`from pydantic.main import BaseModel`

**Comment by lyz-code** [comment] 2021-03-02 09:13
If you don't want to use the `.pylintrc` and are already using `pyproyect.toml`, the line to add there would be:

```
[tool.pylint.'MESSAGES CONTROL']
extension-pkg-whitelist = "pydantic"
```

**Comment by JoyalRebera** [comment] 2021-04-05 07:33
The first thing that you noticed

pydantic BaseModel not found in Fastapi

is related to your linter. I got the same warning when my linter was pylint, so I changed the linter from pylint to mypy and the problem disappeared.

Install mypy via pip

pip install mypy

Open the command palette in VScode

Ctrl+Shift+P

Type this in command palett:

Python: Select Linter

Then Select mypy in the list of linters

**Comment by ssbarnea** [comment] 2021-04-06 09:12
@JoyalRebera You comment does not make any sense. The bug report was about pylint giving an error and you say that using another tool, mypy (which is not quite a linter, more of type checker) solved the problem. I use both, they cover very different issues.

**Comment by JoyalRebera** [comment] 2021-04-07 16:46
> @JoyalRebera You comment does not make any sense. The bug report was about pylint giving an error and you say that using another tool, mypy (which is not quite a linter, more of type checker) solved the problem. I use both, they cover very different issues.



> @JoyalRebera You comment does not make any sense. The bug report was about pylint giving an error and you say that using another tool, mypy (which is not quite a linter, more of type checker) solved the problem. I use both, they cover very different issues.

OK

**Comment by JoyalRebera** [comment] 2021-04-07 16:47
> @JoyalRebera You comment does not make any sense. The bug report was about pylint giving an error and you say that using another tool, mypy (which is not quite a linter, more of type checker) solved the problem. I use both, they cover very different issues.

OK

**Comment by Teagum** [comment] 2022-09-22 13:04
> If you don't want to use the `.pylintrc` and are already using `pyproyect.toml`, the line to add there would be:

I would really appreciate a link to where this is documented.

**Comment by bodograumann** [comment] 2022-09-22 13:24
https://pylint.pycqa.org/en/latest/user_guide/usage/run.html

/pyproject.toml
