### ISSUE TITLE
validation against extra data

### ISSUE THREAD

**Issue by tricosmo** [samuelcolvin/pydantic#2131] opened 2020-11-18 16:19 UTC
### Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://pydantic-docs.helpmanual.io/) and couldn't find an answer
* [x] After submitting this, I commit to one of:
    * Look through open issues and helped at least one other person
    * Hit the "watch" button on this repo to receive notifications and I commit to help at least 2 people that ask questions in the future
    * Implement a Pull Request for a confirmed bug

# Question
Pydantic Version: 1.7.2
First of all, huge thanks to all of you contributing to this amazing library.  I have a question about validation. I have see document about the validators [here](https://pydantic-docs.helpmanual.io/usage/validators/), but none of these really suitable for my situation. Please have a look at below code.
```Python
class ExchangeRate(BaseModel):
    currency: str
    rate: float
    
    @validator('currency')
    def only_these_currencies(cls, v, values, **kwargs):
        external_currencies = kwargs.pop('extra')  # assuming somewhere I can pass this parameter( this parameter may depends on external resources at runtime)
        assert v in external_currencies, f"available currencies are {external_currencies}"
        return v
```

Maybe something like `context` in [marshmellow](https://marshmallow.readthedocs.io/en/stable/why.html?highlight=context#context-aware-serialization)
Thanks in advance.

**Comment by Ronserruya** [comment] 2020-11-19 09:07
Are these `external_currencies` values constantly changing? or do you get it once at the start of the code?

If you have those currencies somewhere you could this

```python
from currencies import external_currencies
from typing import Literal

class ExchangeRate(BaseModel):
    currency: Literal[tuple(external_currencies)]
    rate: float
```

**Comment by tricosmo** [comment] 2020-11-19 09:31
Hi @Ronserruya  

Thanks for your reply. You can think these `external_currencies` are user input data, they are different per each request. And `ExchangeRate` can be a filter of these `external_currencies`, so these must be a subset of it.

Hope this make more sense.
Thanks

**Comment by Ronserruya** [comment] 2020-11-19 13:52
Maybe something like this then? 

```python
from pydantic import BaseModel


class ExchangeRate(BaseModel):
    currency: str
    rate: float

    def __init__(self, external_currencies, **kwargs):
        curr = kwargs.get('currency')
        assert curr in external_currencies, f"available currencies are {external_currencies}"
        super(ExchangeRate, self).__init__(**kwargs)

print(ExchangeRate(external_currencies=['USD','EUR', 'ILS'], currency='ILS', rate=0.5))

ExchangeRate(external_currencies=['USD','EUR', 'ILS'], currency='ABC', rate=0.5) # this fails
```

This is the output

```
currency='ILS' rate=0.5
Traceback (most recent call last):
  File "/Users/ron/Library/Preferences/PyCharm2019.3/scratches/tmp.py", line 15, in <module>
    ExchangeRate(external_currencies=['USD','EUR', 'ILS'], currency='ABC', rate=0.5) # this fails
  File "/Users/ron/Library/Preferences/PyCharm2019.3/scratches/tmp.py", line 10, in __init__
    assert curr in external_currencies, f"available currencies are {external_currencies}"
AssertionError: available currencies are ['USD', 'EUR', 'ILS']

```

**Comment by tricosmo** [comment] 2020-11-19 15:35
Thanks, I am actually thinking about if it is possible to add `pre_validators` on class level, and then it is collected here. https://github.com/samuelcolvin/pydantic/blob/31bc2435d7968fdf8d1f0c5c67f0f851c1bef54e/pydantic/fields.py#L523

imagine I have
```Python
from pydantic import BaseModel
from fastapi import FastAPI
app = FastAPI()


class ExchangeRate(BaseModel):
    currency: str
    rate: float
 
    #??? something like this that will be collected as `pre_validaters` in `populate_validators` function above
    @pre_validator
    def pre_validate(cls, values):
         # values would have be like {'currencies_file': fileobj, 'xrate': {'currency': 'GBP', rate: 1.2}}
         # https://github.com/samuelcolvin/pydantic/blob/31bc2435d7968fdf8d1f0c5c67f0f851c1bef54e/pydantic/fields.py#L559
         # when `validate` function is call, it already has this values. 
    #???
        
@app.post('/currencies')
def foo(currencies_file: UploadFile, xrate: ExchangeRate):
    return {'xrate': xrate, 'currencies': len(currencies_file}

if __name__ == '__main__':
    import uvicorn
    uvicorn.run(app, host='0.0.0.0', port=8000, debug=True)
```

**Comment by PrettyWood** [comment] 2021-01-03 22:59
Duplicate of #515. Probably better to discuss implementation there :)

**Closed by PrettyWood** 2021-01-03 22:59 UTC
Labels: question
