### ISSUE TITLE
Use of compound/composite field 

### ISSUE THREAD

**Issue by stratosgear** [samuelcolvin/pydantic#970] opened 2019-11-06 21:31 UTC
# Question

Please complete:
* OS: **?**
```
uname -a
Linux serenity 5.3.7-arch1-2-ARCH #1 SMP PREEMPT @1572002934 x86_64 GNU/Linux
```

* Python version 
```
print(sys.version)
3.7.4 (default, Oct  4 2019, 06:57:26) 
```

* Pydantic version
```
import pydantic; print(pydantic.VERSION)
0.32.2
```
Having a Pydantic model that contains properly validated fields (let's say `firstname` and `lastname`, how would I be able to create a compound/composite field `fullname` that is composed of the two previous fields (as `f"{firstname} {lastname}"` (or any other way really))?  I know it is redundant information, but I have to have it. 

I am mainly interested in "exporting" that field as part of the `json()` method, withoutt injecting it myself.

Maybe I am misreading the documentation, but I have not found anything useful there. Apologies if I missed it.

What I have as far does not seem to work (I'm including the `orm_mode`, because in my real use case I have to have it, as model is coming from a DB)

```
from pydantic import BaseModel


class User(BaseModel):
    firstname: str = ""
    lastname: str = ""

    @property
    def fullname(self):
        return f"{self.firstname} {self.lastname}"

    class Config:
        orm_mode = True


if __name__ == "__main__":

    u = User(firstname="Joe", lastname="Doe")
    print(f"Fullname: {u.fullname}")
    print(u.json())
```

This only gives:

```
Fullname: Joe Doe
{"firstname": "Joe", "lastname": "Doe"}
```
I would have expected to see `fullname` in the JSON.

The only workaround I have found thus far is to do all the manual work myself:

* Have a  `fullname` field defined in the model (just like `firstname` and `lastname`)
* When I instantiate the model, after it comes out of the DB, **manually** populate the `fullname` field.

But that's a "lot"? of boilerplate to always do.

Isn't there a way to make `fullname` a "permanent" citizen of the model?

**Comment by samuelcolvin** [comment] 2019-11-06 21:44
I think this is a duplicate of #935.

Best to make and comments suggestions there.

**Closed by samuelcolvin** 2019-11-06 21:44 UTC
Labels: question
